//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace WebService.asmx {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.skf.com/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.skf.com/oagis/9", IsNullable=false)]
    public partial class gaiaWs {
        
        private string xmlContentField;
        
        private string messageTypeField;
        
        private string messageTypeVersionField;
        
        private string senderField;
        
        private string transactionIDField;
        
        /// <remarks/>
        public string xmlContent {
            get {
                return this.xmlContentField;
            }
            set {
                this.xmlContentField = value;
            }
        }
        
        /// <remarks/>
        public string messageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
            }
        }
        
        /// <remarks/>
        public string messageTypeVersion {
            get {
                return this.messageTypeVersionField;
            }
            set {
                this.messageTypeVersionField = value;
            }
        }
        
        /// <remarks/>
        public string sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        public string transactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
    }
}
