//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.asmx.LincolnWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="gaiaWs", Namespace="http://www.skf.com/oagis/9")]
    [System.SerializableAttribute()]
    public partial class gaiaWs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object xmlContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object xmlContent {
            get {
                return this.xmlContentField;
            }
            set {
                if ((object.ReferenceEquals(this.xmlContentField, value) != true)) {
                    this.xmlContentField = value;
                    this.RaisePropertyChanged("xmlContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string messageType {
            get {
                return this.messageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.messageTypeField, value) != true)) {
                    this.messageTypeField = value;
                    this.RaisePropertyChanged("messageType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.skf.com/oagis/9/", ConfigurationName="LincolnWebService.LincolnWebSoap")]
    public interface LincolnWebSoap {
        
        // CODEGEN: Generating message contract since message part namespace (http://www.skf.com/oagis/9) does not match the default value (http://www.skf.com/oagis/9/)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.skf.com/oagis/9/GetHostPing", ReplyAction="*")]
        WebService.asmx.LincolnWebService.GetHostPingResponse GetHostPing(WebService.asmx.LincolnWebService.GetHostPingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.skf.com/oagis/9/GetHostPing", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.asmx.LincolnWebService.GetHostPingResponse> GetHostPingAsync(WebService.asmx.LincolnWebService.GetHostPingRequest request);
        
        // CODEGEN: Generating message contract since message part namespace (http://www.skf.com/oagis/9) does not match the default value (http://www.skf.com/oagis/9/)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.skf.com/oagis/9/ProcessPO", ReplyAction="*")]
        WebService.asmx.LincolnWebService.ProcessPOResponse ProcessPO(WebService.asmx.LincolnWebService.ProcessPORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.skf.com/oagis/9/ProcessPO", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.asmx.LincolnWebService.ProcessPOResponse> ProcessPOAsync(WebService.asmx.LincolnWebService.ProcessPORequest request);
        
        // CODEGEN: Generating message contract since message part namespace (http://www.skf.com/oagis/9) does not match the default value (http://www.skf.com/oagis/9/)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.skf.com/oagis/9/GetListSalesOrder", ReplyAction="*")]
        WebService.asmx.LincolnWebService.GetListSalesOrderResponse GetListSalesOrder(WebService.asmx.LincolnWebService.GetListSalesOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.skf.com/oagis/9/GetListSalesOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.asmx.LincolnWebService.GetListSalesOrderResponse> GetListSalesOrderAsync(WebService.asmx.LincolnWebService.GetListSalesOrderRequest request);
        
        // CODEGEN: Generating message contract since message part namespace (http://www.skf.com/oagis/9) does not match the default value (http://www.skf.com/oagis/9/)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.skf.com/oagis/9/GetSalesOrder", ReplyAction="*")]
        WebService.asmx.LincolnWebService.GetSalesOrderResponse GetSalesOrder(WebService.asmx.LincolnWebService.GetSalesOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.skf.com/oagis/9/GetSalesOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.asmx.LincolnWebService.GetSalesOrderResponse> GetSalesOrderAsync(WebService.asmx.LincolnWebService.GetSalesOrderRequest request);
        
        // CODEGEN: Generating message contract since message part namespace (http://www.skf.com/oagis/9) does not match the default value (http://www.skf.com/oagis/9/)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.skf.com/oagis/9/GetPriceList", ReplyAction="*")]
        WebService.asmx.LincolnWebService.GetPriceListResponse GetPriceList(WebService.asmx.LincolnWebService.GetPriceListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.skf.com/oagis/9/GetPriceList", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.asmx.LincolnWebService.GetPriceListResponse> GetPriceListAsync(WebService.asmx.LincolnWebService.GetPriceListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHostPing", WrapperNamespace="http://www.skf.com/oagis/9/", IsWrapped=true)]
    public partial class GetHostPingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.skf.com/oagis/9", Order=0)]
        public WebService.asmx.LincolnWebService.gaiaWs gaiaWs;
        
        public GetHostPingRequest() {
        }
        
        public GetHostPingRequest(WebService.asmx.LincolnWebService.gaiaWs gaiaWs) {
            this.gaiaWs = gaiaWs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHostPingResponse", WrapperNamespace="http://www.skf.com/oagis/9/", IsWrapped=true)]
    public partial class GetHostPingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.skf.com/oagis/9/", Order=0)]
        public System.Xml.Linq.XElement GetHostPingResult;
        
        public GetHostPingResponse() {
        }
        
        public GetHostPingResponse(System.Xml.Linq.XElement GetHostPingResult) {
            this.GetHostPingResult = GetHostPingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessPO", WrapperNamespace="http://www.skf.com/oagis/9/", IsWrapped=true)]
    public partial class ProcessPORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.skf.com/oagis/9", Order=0)]
        public WebService.asmx.LincolnWebService.gaiaWs gaiaWs;
        
        public ProcessPORequest() {
        }
        
        public ProcessPORequest(WebService.asmx.LincolnWebService.gaiaWs gaiaWs) {
            this.gaiaWs = gaiaWs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessPOResponse", WrapperNamespace="http://www.skf.com/oagis/9/", IsWrapped=true)]
    public partial class ProcessPOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.skf.com/oagis/9/", Order=0)]
        public System.Xml.Linq.XElement ProcessPOResult;
        
        public ProcessPOResponse() {
        }
        
        public ProcessPOResponse(System.Xml.Linq.XElement ProcessPOResult) {
            this.ProcessPOResult = ProcessPOResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetListSalesOrder", WrapperNamespace="http://www.skf.com/oagis/9/", IsWrapped=true)]
    public partial class GetListSalesOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.skf.com/oagis/9", Order=0)]
        public WebService.asmx.LincolnWebService.gaiaWs gaiaWs;
        
        public GetListSalesOrderRequest() {
        }
        
        public GetListSalesOrderRequest(WebService.asmx.LincolnWebService.gaiaWs gaiaWs) {
            this.gaiaWs = gaiaWs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetListSalesOrderResponse", WrapperNamespace="http://www.skf.com/oagis/9/", IsWrapped=true)]
    public partial class GetListSalesOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.skf.com/oagis/9/", Order=0)]
        public System.Xml.Linq.XElement GetListSalesOrderResult;
        
        public GetListSalesOrderResponse() {
        }
        
        public GetListSalesOrderResponse(System.Xml.Linq.XElement GetListSalesOrderResult) {
            this.GetListSalesOrderResult = GetListSalesOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSalesOrder", WrapperNamespace="http://www.skf.com/oagis/9/", IsWrapped=true)]
    public partial class GetSalesOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.skf.com/oagis/9", Order=0)]
        public WebService.asmx.LincolnWebService.gaiaWs gaiaWs;
        
        public GetSalesOrderRequest() {
        }
        
        public GetSalesOrderRequest(WebService.asmx.LincolnWebService.gaiaWs gaiaWs) {
            this.gaiaWs = gaiaWs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSalesOrderResponse", WrapperNamespace="http://www.skf.com/oagis/9/", IsWrapped=true)]
    public partial class GetSalesOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.skf.com/oagis/9/", Order=0)]
        public System.Xml.Linq.XElement GetSalesOrderResult;
        
        public GetSalesOrderResponse() {
        }
        
        public GetSalesOrderResponse(System.Xml.Linq.XElement GetSalesOrderResult) {
            this.GetSalesOrderResult = GetSalesOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPriceList", WrapperNamespace="http://www.skf.com/oagis/9/", IsWrapped=true)]
    public partial class GetPriceListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.skf.com/oagis/9", Order=0)]
        public WebService.asmx.LincolnWebService.gaiaWs gaiaWs;
        
        public GetPriceListRequest() {
        }
        
        public GetPriceListRequest(WebService.asmx.LincolnWebService.gaiaWs gaiaWs) {
            this.gaiaWs = gaiaWs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPriceListResponse", WrapperNamespace="http://www.skf.com/oagis/9/", IsWrapped=true)]
    public partial class GetPriceListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.skf.com/oagis/9/", Order=0)]
        public System.Xml.Linq.XElement GetPriceListResult;
        
        public GetPriceListResponse() {
        }
        
        public GetPriceListResponse(System.Xml.Linq.XElement GetPriceListResult) {
            this.GetPriceListResult = GetPriceListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LincolnWebSoapChannel : WebService.asmx.LincolnWebService.LincolnWebSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LincolnWebSoapClient : System.ServiceModel.ClientBase<WebService.asmx.LincolnWebService.LincolnWebSoap>, WebService.asmx.LincolnWebService.LincolnWebSoap {
        
        public LincolnWebSoapClient() {
        }
        
        public LincolnWebSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LincolnWebSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LincolnWebSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LincolnWebSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.asmx.LincolnWebService.GetHostPingResponse WebService.asmx.LincolnWebService.LincolnWebSoap.GetHostPing(WebService.asmx.LincolnWebService.GetHostPingRequest request) {
            return base.Channel.GetHostPing(request);
        }
        
        public System.Xml.Linq.XElement GetHostPing(WebService.asmx.LincolnWebService.gaiaWs gaiaWs) {
            WebService.asmx.LincolnWebService.GetHostPingRequest inValue = new WebService.asmx.LincolnWebService.GetHostPingRequest();
            inValue.gaiaWs = gaiaWs;
            WebService.asmx.LincolnWebService.GetHostPingResponse retVal = ((WebService.asmx.LincolnWebService.LincolnWebSoap)(this)).GetHostPing(inValue);
            return retVal.GetHostPingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService.asmx.LincolnWebService.GetHostPingResponse> WebService.asmx.LincolnWebService.LincolnWebSoap.GetHostPingAsync(WebService.asmx.LincolnWebService.GetHostPingRequest request) {
            return base.Channel.GetHostPingAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService.asmx.LincolnWebService.GetHostPingResponse> GetHostPingAsync(WebService.asmx.LincolnWebService.gaiaWs gaiaWs) {
            WebService.asmx.LincolnWebService.GetHostPingRequest inValue = new WebService.asmx.LincolnWebService.GetHostPingRequest();
            inValue.gaiaWs = gaiaWs;
            return ((WebService.asmx.LincolnWebService.LincolnWebSoap)(this)).GetHostPingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.asmx.LincolnWebService.ProcessPOResponse WebService.asmx.LincolnWebService.LincolnWebSoap.ProcessPO(WebService.asmx.LincolnWebService.ProcessPORequest request) {
            return base.Channel.ProcessPO(request);
        }
        
        public System.Xml.Linq.XElement ProcessPO(WebService.asmx.LincolnWebService.gaiaWs gaiaWs) {
            WebService.asmx.LincolnWebService.ProcessPORequest inValue = new WebService.asmx.LincolnWebService.ProcessPORequest();
            inValue.gaiaWs = gaiaWs;
            WebService.asmx.LincolnWebService.ProcessPOResponse retVal = ((WebService.asmx.LincolnWebService.LincolnWebSoap)(this)).ProcessPO(inValue);
            return retVal.ProcessPOResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService.asmx.LincolnWebService.ProcessPOResponse> WebService.asmx.LincolnWebService.LincolnWebSoap.ProcessPOAsync(WebService.asmx.LincolnWebService.ProcessPORequest request) {
            return base.Channel.ProcessPOAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService.asmx.LincolnWebService.ProcessPOResponse> ProcessPOAsync(WebService.asmx.LincolnWebService.gaiaWs gaiaWs) {
            WebService.asmx.LincolnWebService.ProcessPORequest inValue = new WebService.asmx.LincolnWebService.ProcessPORequest();
            inValue.gaiaWs = gaiaWs;
            return ((WebService.asmx.LincolnWebService.LincolnWebSoap)(this)).ProcessPOAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.asmx.LincolnWebService.GetListSalesOrderResponse WebService.asmx.LincolnWebService.LincolnWebSoap.GetListSalesOrder(WebService.asmx.LincolnWebService.GetListSalesOrderRequest request) {
            return base.Channel.GetListSalesOrder(request);
        }
        
        public System.Xml.Linq.XElement GetListSalesOrder(WebService.asmx.LincolnWebService.gaiaWs gaiaWs) {
            WebService.asmx.LincolnWebService.GetListSalesOrderRequest inValue = new WebService.asmx.LincolnWebService.GetListSalesOrderRequest();
            inValue.gaiaWs = gaiaWs;
            WebService.asmx.LincolnWebService.GetListSalesOrderResponse retVal = ((WebService.asmx.LincolnWebService.LincolnWebSoap)(this)).GetListSalesOrder(inValue);
            return retVal.GetListSalesOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService.asmx.LincolnWebService.GetListSalesOrderResponse> WebService.asmx.LincolnWebService.LincolnWebSoap.GetListSalesOrderAsync(WebService.asmx.LincolnWebService.GetListSalesOrderRequest request) {
            return base.Channel.GetListSalesOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService.asmx.LincolnWebService.GetListSalesOrderResponse> GetListSalesOrderAsync(WebService.asmx.LincolnWebService.gaiaWs gaiaWs) {
            WebService.asmx.LincolnWebService.GetListSalesOrderRequest inValue = new WebService.asmx.LincolnWebService.GetListSalesOrderRequest();
            inValue.gaiaWs = gaiaWs;
            return ((WebService.asmx.LincolnWebService.LincolnWebSoap)(this)).GetListSalesOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.asmx.LincolnWebService.GetSalesOrderResponse WebService.asmx.LincolnWebService.LincolnWebSoap.GetSalesOrder(WebService.asmx.LincolnWebService.GetSalesOrderRequest request) {
            return base.Channel.GetSalesOrder(request);
        }
        
        public System.Xml.Linq.XElement GetSalesOrder(WebService.asmx.LincolnWebService.gaiaWs gaiaWs) {
            WebService.asmx.LincolnWebService.GetSalesOrderRequest inValue = new WebService.asmx.LincolnWebService.GetSalesOrderRequest();
            inValue.gaiaWs = gaiaWs;
            WebService.asmx.LincolnWebService.GetSalesOrderResponse retVal = ((WebService.asmx.LincolnWebService.LincolnWebSoap)(this)).GetSalesOrder(inValue);
            return retVal.GetSalesOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService.asmx.LincolnWebService.GetSalesOrderResponse> WebService.asmx.LincolnWebService.LincolnWebSoap.GetSalesOrderAsync(WebService.asmx.LincolnWebService.GetSalesOrderRequest request) {
            return base.Channel.GetSalesOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService.asmx.LincolnWebService.GetSalesOrderResponse> GetSalesOrderAsync(WebService.asmx.LincolnWebService.gaiaWs gaiaWs) {
            WebService.asmx.LincolnWebService.GetSalesOrderRequest inValue = new WebService.asmx.LincolnWebService.GetSalesOrderRequest();
            inValue.gaiaWs = gaiaWs;
            return ((WebService.asmx.LincolnWebService.LincolnWebSoap)(this)).GetSalesOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.asmx.LincolnWebService.GetPriceListResponse WebService.asmx.LincolnWebService.LincolnWebSoap.GetPriceList(WebService.asmx.LincolnWebService.GetPriceListRequest request) {
            return base.Channel.GetPriceList(request);
        }
        
        public System.Xml.Linq.XElement GetPriceList(WebService.asmx.LincolnWebService.gaiaWs gaiaWs) {
            WebService.asmx.LincolnWebService.GetPriceListRequest inValue = new WebService.asmx.LincolnWebService.GetPriceListRequest();
            inValue.gaiaWs = gaiaWs;
            WebService.asmx.LincolnWebService.GetPriceListResponse retVal = ((WebService.asmx.LincolnWebService.LincolnWebSoap)(this)).GetPriceList(inValue);
            return retVal.GetPriceListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService.asmx.LincolnWebService.GetPriceListResponse> WebService.asmx.LincolnWebService.LincolnWebSoap.GetPriceListAsync(WebService.asmx.LincolnWebService.GetPriceListRequest request) {
            return base.Channel.GetPriceListAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService.asmx.LincolnWebService.GetPriceListResponse> GetPriceListAsync(WebService.asmx.LincolnWebService.gaiaWs gaiaWs) {
            WebService.asmx.LincolnWebService.GetPriceListRequest inValue = new WebService.asmx.LincolnWebService.GetPriceListRequest();
            inValue.gaiaWs = gaiaWs;
            return ((WebService.asmx.LincolnWebService.LincolnWebSoap)(this)).GetPriceListAsync(inValue);
        }
    }
}
