namespace WebService.asmx.getPriceList
{

    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class NOUN
    {

        private string valueField;

        private string valueField1;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField1;
            }
            set
            {
                this.valueField1 = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class REVISION
    {

        private string valueField;

        private string valueField1;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField1;
            }
            set
            {
                this.valueField1 = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class SITELEVEL
    {

        private string indexField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class USERAREA
    {

        private System.Xml.XmlNode[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class VERB
    {

        private string valueField;

        private string valueField1;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField1;
            }
            set
            {
                this.valueField1 = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class AMOUNT
    {

        private string vALUEField;

        private string nUMOFDECField;

        private string sIGNField;

        private string cURRENCYField;

        private string dRCRField;

        private AMOUNTQualifier qualifierField;

        private AMOUNTType typeField;

        private bool typeFieldSpecified;

        private string indexField;

        /// <remarks/>
        public string VALUE
        {
            get
            {
                return this.vALUEField;
            }
            set
            {
                this.vALUEField = value;
            }
        }

        /// <remarks/>
        public string NUMOFDEC
        {
            get
            {
                return this.nUMOFDECField;
            }
            set
            {
                this.nUMOFDECField = value;
            }
        }

        /// <remarks/>
        public string SIGN
        {
            get
            {
                return this.sIGNField;
            }
            set
            {
                this.sIGNField = value;
            }
        }

        /// <remarks/>
        public string CURRENCY
        {
            get
            {
                return this.cURRENCYField;
            }
            set
            {
                this.cURRENCYField = value;
            }
        }

        /// <remarks/>
        public string DRCR
        {
            get
            {
                return this.dRCRField;
            }
            set
            {
                this.dRCRField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AMOUNTQualifier qualifier
        {
            get
            {
                return this.qualifierField;
            }
            set
            {
                this.qualifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AMOUNTType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
    public enum AMOUNTQualifier
    {

        /// <remarks/>
        ACTUAL,

        /// <remarks/>
        APPRVORD,

        /// <remarks/>
        AVAILABLE,

        /// <remarks/>
        BUDGET,

        /// <remarks/>
        COMMISSION,

        /// <remarks/>
        DECLAREVAL,

        /// <remarks/>
        DSCPRCNT,

        /// <remarks/>
        DSCVALUE,

        /// <remarks/>
        DISCNT,

        /// <remarks/>
        DOCUMENT,

        /// <remarks/>
        ESTENGIMP,

        /// <remarks/>
        ESTFREIGHT,

        /// <remarks/>
        ESTHRS,

        /// <remarks/>
        ESTIMATE,

        /// <remarks/>
        ESTMANIMP,

        /// <remarks/>
        ESTUCOST,

        /// <remarks/>
        EXTENDED,

        /// <remarks/>
        FREIGHT,

        /// <remarks/>
        ITEM,

        /// <remarks/>
        OPENITEM,

        /// <remarks/>
        ORDER,

        /// <remarks/>
        ORDLIMIT,

        /// <remarks/>
        PAYRATE,

        /// <remarks/>
        RATE,

        /// <remarks/>
        PRCBRK,

        /// <remarks/>
        TAX,

        /// <remarks/>
        TAXBASE,

        /// <remarks/>
        TOTAL,

        /// <remarks/>
        TOTLIMIT,

        /// <remarks/>
        OTHER,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("COLINX.DISCMULT")]
        COLINXDISCMULT,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
    public enum AMOUNTType
    {

        /// <remarks/>
        T,

        /// <remarks/>
        F,

        /// <remarks/>
        OTHER,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class BSR
    {

        private VERB vERBField;

        private NOUN nOUNField;

        private REVISION rEVISIONField;

        /// <remarks/>
        public VERB VERB
        {
            get
            {
                return this.vERBField;
            }
            set
            {
                this.vERBField = value;
            }
        }

        /// <remarks/>
        public NOUN NOUN
        {
            get
            {
                return this.nOUNField;
            }
            set
            {
                this.nOUNField = value;
            }
        }

        /// <remarks/>
        public REVISION REVISION
        {
            get
            {
                return this.rEVISIONField;
            }
            set
            {
                this.rEVISIONField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class CNTROLAREA
    {

        private BSR bSRField;

        private SENDER sENDERField;

        private DATETIME dATETIMEField;

        /// <remarks/>
        public BSR BSR
        {
            get
            {
                return this.bSRField;
            }
            set
            {
                this.bSRField = value;
            }
        }

        /// <remarks/>
        public SENDER SENDER
        {
            get
            {
                return this.sENDERField;
            }
            set
            {
                this.sENDERField = value;
            }
        }

        /// <remarks/>
        public DATETIME DATETIME
        {
            get
            {
                return this.dATETIMEField;
            }
            set
            {
                this.dATETIMEField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class SENDER
    {

        private string lOGICALIDField;

        private string cOMPONENTField;

        private string tASKField;

        private string rEFERENCEIDField;

        private string cONFIRMATIONField;

        private string lANGUAGEField;

        private string cODEPAGEField;

        private string aUTHIDField;

        /// <remarks/>
        public string LOGICALID
        {
            get
            {
                return this.lOGICALIDField;
            }
            set
            {
                this.lOGICALIDField = value;
            }
        }

        /// <remarks/>
        public string COMPONENT
        {
            get
            {
                return this.cOMPONENTField;
            }
            set
            {
                this.cOMPONENTField = value;
            }
        }

        /// <remarks/>
        public string TASK
        {
            get
            {
                return this.tASKField;
            }
            set
            {
                this.tASKField = value;
            }
        }

        /// <remarks/>
        public string REFERENCEID
        {
            get
            {
                return this.rEFERENCEIDField;
            }
            set
            {
                this.rEFERENCEIDField = value;
            }
        }

        /// <remarks/>
        public string CONFIRMATION
        {
            get
            {
                return this.cONFIRMATIONField;
            }
            set
            {
                this.cONFIRMATIONField = value;
            }
        }

        /// <remarks/>
        public string LANGUAGE
        {
            get
            {
                return this.lANGUAGEField;
            }
            set
            {
                this.lANGUAGEField = value;
            }
        }

        /// <remarks/>
        public string CODEPAGE
        {
            get
            {
                return this.cODEPAGEField;
            }
            set
            {
                this.cODEPAGEField = value;
            }
        }

        /// <remarks/>
        public string AUTHID
        {
            get
            {
                return this.aUTHIDField;
            }
            set
            {
                this.aUTHIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class DATETIME
    {

        private string yEARField;

        private string mONTHField;

        private string dAYField;

        private string hOURField;

        private string mINUTEField;

        private string sECONDField;

        private string sUBSECONDField;

        private string tIMEZONEField;

        private DATETIMEQualifier qualifierField;

        private DATETIMEType typeField;

        private bool typeFieldSpecified;

        private string indexField;

        /// <remarks/>
        public string YEAR
        {
            get
            {
                return this.yEARField;
            }
            set
            {
                this.yEARField = value;
            }
        }

        /// <remarks/>
        public string MONTH
        {
            get
            {
                return this.mONTHField;
            }
            set
            {
                this.mONTHField = value;
            }
        }

        /// <remarks/>
        public string DAY
        {
            get
            {
                return this.dAYField;
            }
            set
            {
                this.dAYField = value;
            }
        }

        /// <remarks/>
        public string HOUR
        {
            get
            {
                return this.hOURField;
            }
            set
            {
                this.hOURField = value;
            }
        }

        /// <remarks/>
        public string MINUTE
        {
            get
            {
                return this.mINUTEField;
            }
            set
            {
                this.mINUTEField = value;
            }
        }

        /// <remarks/>
        public string SECOND
        {
            get
            {
                return this.sECONDField;
            }
            set
            {
                this.sECONDField = value;
            }
        }

        /// <remarks/>
        public string SUBSECOND
        {
            get
            {
                return this.sUBSECONDField;
            }
            set
            {
                this.sUBSECONDField = value;
            }
        }

        /// <remarks/>
        public string TIMEZONE
        {
            get
            {
                return this.tIMEZONEField;
            }
            set
            {
                this.tIMEZONEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DATETIMEQualifier qualifier
        {
            get
            {
                return this.qualifierField;
            }
            set
            {
                this.qualifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DATETIMEType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
    public enum DATETIMEQualifier
    {

        /// <remarks/>
        ACCOUNTING,

        /// <remarks/>
        ACTEND,

        /// <remarks/>
        ACTSTART,

        /// <remarks/>
        APPREQ,

        /// <remarks/>
        APPROVAL,

        /// <remarks/>
        AVAILABLE,

        /// <remarks/>
        BKTEND,

        /// <remarks/>
        BKTSTART,

        /// <remarks/>
        CANCEL,

        /// <remarks/>
        CHANGEDATE,

        /// <remarks/>
        COMPDATE,

        /// <remarks/>
        CREATION,

        /// <remarks/>
        CUMULATIVE,

        /// <remarks/>
        DELIVACT,

        /// <remarks/>
        DELIVSCHED,

        /// <remarks/>
        DISCNT,

        /// <remarks/>
        DOCUMENT,

        /// <remarks/>
        DUE,

        /// <remarks/>
        EARLSTEFF,

        /// <remarks/>
        EARLSTSHIP,

        /// <remarks/>
        EFFECTIVE,

        /// <remarks/>
        ENGCHG,

        /// <remarks/>
        EXECFINISH,

        /// <remarks/>
        EXECSTART,

        /// <remarks/>
        EXPIRATION,

        /// <remarks/>
        FAILDATE,

        /// <remarks/>
        FORECASTF,

        /// <remarks/>
        FORECASTS,

        /// <remarks/>
        FROM,

        /// <remarks/>
        GENERATION,

        /// <remarks/>
        IMPL,

        /// <remarks/>
        INVOICE,

        /// <remarks/>
        LABORFINSH,

        /// <remarks/>
        LABORSTART,

        /// <remarks/>
        LASTUSED,

        /// <remarks/>
        LOADING,

        /// <remarks/>
        MATCHING,

        /// <remarks/>
        MSMENTDATE,

        /// <remarks/>
        NEEDDELV,

        /// <remarks/>
        OPFINISH,

        /// <remarks/>
        OPSTART,

        /// <remarks/>
        PAYEND,

        /// <remarks/>
        PLANEND,

        /// <remarks/>
        PLANSTART,

        /// <remarks/>
        PO,

        /// <remarks/>
        PROMDELV,

        /// <remarks/>
        PROMSHIP,

        /// <remarks/>
        PYMTTERM,

        /// <remarks/>
        RECEIVED,

        /// <remarks/>
        REPORTDATE,

        /// <remarks/>
        REPORTNGFN,

        /// <remarks/>
        REPORTNGST,

        /// <remarks/>
        REQUIRED,

        /// <remarks/>
        RESORCDWNF,

        /// <remarks/>
        RESORCDWNS,

        /// <remarks/>
        RSPDDATE,

        /// <remarks/>
        RSPDOCGEN,

        /// <remarks/>
        SCHEND,

        /// <remarks/>
        SCHSTART,

        /// <remarks/>
        SETUPFINSH,

        /// <remarks/>
        SETUPSTART,

        /// <remarks/>
        SHIP,

        /// <remarks/>
        SHIPSCHED,

        /// <remarks/>
        STATUSDATE,

        /// <remarks/>
        TEARDOWNF,

        /// <remarks/>
        TEARDOWNS,

        /// <remarks/>
        TO,

        /// <remarks/>
        OTHER,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("COLINX.CARDEXP")]
        COLINXCARDEXP,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("COLINX.REQUESTED")]
        COLINXREQUESTED,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_get_pricelist_002")]
    public enum DATETIMEType
    {

        /// <remarks/>
        T,

        /// <remarks/>
        F,

        /// <remarks/>
        OTHER,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class OPERAMT
    {

        private string vALUEField;

        private string nUMOFDECField;

        private string sIGNField;

        private string cURRENCYField;

        private string uOMVALUEField;

        private string uOMNUMDECField;

        private string uOMField;

        private OPERAMTQualifier qualifierField;

        private OPERAMTType typeField;

        /// <remarks/>
        public string VALUE
        {
            get
            {
                return this.vALUEField;
            }
            set
            {
                this.vALUEField = value;
            }
        }

        /// <remarks/>
        public string NUMOFDEC
        {
            get
            {
                return this.nUMOFDECField;
            }
            set
            {
                this.nUMOFDECField = value;
            }
        }

        /// <remarks/>
        public string SIGN
        {
            get
            {
                return this.sIGNField;
            }
            set
            {
                this.sIGNField = value;
            }
        }

        /// <remarks/>
        public string CURRENCY
        {
            get
            {
                return this.cURRENCYField;
            }
            set
            {
                this.cURRENCYField = value;
            }
        }

        /// <remarks/>
        public string UOMVALUE
        {
            get
            {
                return this.uOMVALUEField;
            }
            set
            {
                this.uOMVALUEField = value;
            }
        }

        /// <remarks/>
        public string UOMNUMDEC
        {
            get
            {
                return this.uOMNUMDECField;
            }
            set
            {
                this.uOMNUMDECField = value;
            }
        }

        /// <remarks/>
        public string UOM
        {
            get
            {
                return this.uOMField;
            }
            set
            {
                this.uOMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public OPERAMTQualifier qualifier
        {
            get
            {
                return this.qualifierField;
            }
            set
            {
                this.qualifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public OPERAMTType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
    public enum OPERAMTQualifier
    {

        /// <remarks/>
        COST,

        /// <remarks/>
        EXTENDED,

        /// <remarks/>
        FREIGHT,

        /// <remarks/>
        UNIT,

        /// <remarks/>
        OTHER,

        /// <remarks/>
        LPRICE,

        /// <remarks/>
        RVPRICE,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
    public enum OPERAMTType
    {

        /// <remarks/>
        T,

        /// <remarks/>
        F,

        /// <remarks/>
        OTHER,

        /// <remarks/>
        LPRICE,

        /// <remarks/>
        RVPRICE,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class QUANTITY
    {

        private string vALUEField;

        private string nUMOFDECField;

        private string sIGNField;

        private string uOMField;

        private QUANTITYQualifier qualifierField;

        /// <remarks/>
        public string VALUE
        {
            get
            {
                return this.vALUEField;
            }
            set
            {
                this.vALUEField = value;
            }
        }

        /// <remarks/>
        public string NUMOFDEC
        {
            get
            {
                return this.nUMOFDECField;
            }
            set
            {
                this.nUMOFDECField = value;
            }
        }

        /// <remarks/>
        public string SIGN
        {
            get
            {
                return this.sIGNField;
            }
            set
            {
                this.sIGNField = value;
            }
        }

        /// <remarks/>
        public string UOM
        {
            get
            {
                return this.uOMField;
            }
            set
            {
                this.uOMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public QUANTITYQualifier qualifier
        {
            get
            {
                return this.qualifierField;
            }
            set
            {
                this.qualifierField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
    public enum QUANTITYQualifier
    {

        /// <remarks/>
        ACCEPTED,

        /// <remarks/>
        ACTDUR,

        /// <remarks/>
        ACTHRS,

        /// <remarks/>
        ALLOCATED,

        /// <remarks/>
        ALLOWEDWT,

        /// <remarks/>
        AVAILABLE,

        /// <remarks/>
        AVGRUNSIZE,

        /// <remarks/>
        BACKORDERD,

        /// <remarks/>
        BATCHSIZE,

        /// <remarks/>
        BATCHTIME,

        /// <remarks/>
        BLOCKED,

        /// <remarks/>
        BREAKTIME,

        /// <remarks/>
        CAPPERCENT,

        /// <remarks/>
        CATCHWEGHT,

        /// <remarks/>
        COMMISSION,

        /// <remarks/>
        COMPLETED,

        /// <remarks/>
        CUMULATIVE,

        /// <remarks/>
        DELIVERED,

        /// <remarks/>
        DURATION,

        /// <remarks/>
        DUROVER,

        /// <remarks/>
        DURUNDER,

        /// <remarks/>
        EMPLOYEES,

        /// <remarks/>
        EMPREQD,

        /// <remarks/>
        ESTDUR,

        /// <remarks/>
        ESTHRS,

        /// <remarks/>
        ESTWEIGHT,

        /// <remarks/>
        FILENAME,

        /// <remarks/>
        FILESIZE,

        /// <remarks/>
        FIXEDTIME,

        /// <remarks/>
        HEIGHT,

        /// <remarks/>
        INSPECTED,

        /// <remarks/>
        INSPECTION,

        /// <remarks/>
        ITEM,

        /// <remarks/>
        LDTMOFFSET,

        /// <remarks/>
        LENGTH,

        /// <remarks/>
        LABOR,

        /// <remarks/>
        LOADINGWT,

        /// <remarks/>
        LOTSIZEMAX,

        /// <remarks/>
        LOTSIZEMIN,

        /// <remarks/>
        LOTSIZEMLT,

        /// <remarks/>
        LOWERLIMIT,

        /// <remarks/>
        MACHINEHRS,

        /// <remarks/>
        MAXIMUM,

        /// <remarks/>
        MAXPARLTM,

        /// <remarks/>
        MINIMUM,

        /// <remarks/>
        MOVETIME,

        /// <remarks/>
        MSMENT,

        /// <remarks/>
        MULTIPLIER,

        /// <remarks/>
        NETWEIGHT,

        /// <remarks/>
        OPEN,

        /// <remarks/>
        ORDERED,

        /// <remarks/>
        OTHERREJ,

        /// <remarks/>
        OVERSHIP,

        /// <remarks/>
        PACKING,

        /// <remarks/>
        PERCENT,

        /// <remarks/>
        PERCENTREQ,

        /// <remarks/>
        PERSHBNOPR,

        /// <remarks/>
        PERSHWIOPR,

        /// <remarks/>
        PLNDPRCT,

        /// <remarks/>
        PRCBRK,

        /// <remarks/>
        PRIOR,

        /// <remarks/>
        QUEUETIME,

        /// <remarks/>
        RATE,

        /// <remarks/>
        RECEIVED,

        /// <remarks/>
        REJECTED,

        /// <remarks/>
        REJPERCENT,

        /// <remarks/>
        REMDUR,

        /// <remarks/>
        REMHRS,

        /// <remarks/>
        REQUIRED,

        /// <remarks/>
        RETURNED,

        /// <remarks/>
        REWORK,

        /// <remarks/>
        RUNTIME,

        /// <remarks/>
        SCRAP,

        /// <remarks/>
        SETUPTIME,

        /// <remarks/>
        SHELFLIFE,

        /// <remarks/>
        SHIPPED,

        /// <remarks/>
        SHIPUNIT,

        /// <remarks/>
        TEARDOWN,

        /// <remarks/>
        TOOLREQD,

        /// <remarks/>
        TOTWEIGHT,

        /// <remarks/>
        TRANSFRLOT,

        /// <remarks/>
        UNDERSHIP,

        /// <remarks/>
        UNIT,

        /// <remarks/>
        UPPERLIMIT,

        /// <remarks/>
        VOLUME,

        /// <remarks/>
        WAITTIME,

        /// <remarks/>
        WEIGHT,

        /// <remarks/>
        WIDTH,

        /// <remarks/>
        OTHER,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("COLINX.TOTWEIGHT")]
        COLINXTOTWEIGHT,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("COLINX.ALLOWED")]
        COLINXALLOWED,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("COLINX.ORDERED")]
        COLINXORDERED,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("COLINX.REMAIN")]
        COLINXREMAIN,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class NAME
    {

        private string indexField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class COLINX_PREFERENCE
    {

        private string cOLINX_PREFNAMEField;

        private string cOLINX_PREFVALUEField;

        private string cOLINX_PREFDESCField;

        /// <remarks/>
        public string COLINX_PREFNAME
        {
            get
            {
                return this.cOLINX_PREFNAMEField;
            }
            set
            {
                this.cOLINX_PREFNAMEField = value;
            }
        }

        /// <remarks/>
        public string COLINX_PREFVALUE
        {
            get
            {
                return this.cOLINX_PREFVALUEField;
            }
            set
            {
                this.cOLINX_PREFVALUEField = value;
            }
        }

        /// <remarks/>
        public string COLINX_PREFDESC
        {
            get
            {
                return this.cOLINX_PREFDESCField;
            }
            set
            {
                this.cOLINX_PREFDESCField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class COLINX_PARTNER_USERAREA
    {

        private COLINX_PREFERENCE[] cOLINX_PREFERENCEField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("COLINX_PREFERENCE")]
        public COLINX_PREFERENCE[] COLINX_PREFERENCE
        {
            get
            {
                return this.cOLINX_PREFERENCEField;
            }
            set
            {
                this.cOLINX_PREFERENCEField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class ADDRLINE
    {

        private string indexField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class FAX
    {

        private string indexField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class TELEPHONE
    {

        private string indexField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class COLINX_ADDRESS_USERAREA
    {

        private string cOLINX_LEGACYKEYField;

        /// <remarks/>
        public string COLINX_LEGACYKEY
        {
            get
            {
                return this.cOLINX_LEGACYKEYField;
            }
            set
            {
                this.cOLINX_LEGACYKEYField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class ADDRESS
    {

        private ADDRLINE[] aDDRLINEField;

        private string aDDRTYPEField;

        private string cITYField;

        private string cOUNTRYField;

        private string cOUNTYField;

        private string dESCRIPTNField;

        private FAX[] fAXField;

        private string pOSTALCODEField;

        private string rEGIONField;

        private string sTATEPROVNField;

        private string tAXJRSDCTNField;

        private TELEPHONE[] tELEPHONEField;

        private string uRLField;

        private COLINX_ADDRESS_USERAREA cOLINX_ADDRESS_USERAREAField;

        private string returndataField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADDRLINE")]
        public ADDRLINE[] ADDRLINE
        {
            get
            {
                return this.aDDRLINEField;
            }
            set
            {
                this.aDDRLINEField = value;
            }
        }

        /// <remarks/>
        public string ADDRTYPE
        {
            get
            {
                return this.aDDRTYPEField;
            }
            set
            {
                this.aDDRTYPEField = value;
            }
        }

        /// <remarks/>
        public string CITY
        {
            get
            {
                return this.cITYField;
            }
            set
            {
                this.cITYField = value;
            }
        }

        /// <remarks/>
        public string COUNTRY
        {
            get
            {
                return this.cOUNTRYField;
            }
            set
            {
                this.cOUNTRYField = value;
            }
        }

        /// <remarks/>
        public string COUNTY
        {
            get
            {
                return this.cOUNTYField;
            }
            set
            {
                this.cOUNTYField = value;
            }
        }

        /// <remarks/>
        public string DESCRIPTN
        {
            get
            {
                return this.dESCRIPTNField;
            }
            set
            {
                this.dESCRIPTNField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FAX")]
        public FAX[] FAX
        {
            get
            {
                return this.fAXField;
            }
            set
            {
                this.fAXField = value;
            }
        }

        /// <remarks/>
        public string POSTALCODE
        {
            get
            {
                return this.pOSTALCODEField;
            }
            set
            {
                this.pOSTALCODEField = value;
            }
        }

        /// <remarks/>
        public string REGION
        {
            get
            {
                return this.rEGIONField;
            }
            set
            {
                this.rEGIONField = value;
            }
        }

        /// <remarks/>
        public string STATEPROVN
        {
            get
            {
                return this.sTATEPROVNField;
            }
            set
            {
                this.sTATEPROVNField = value;
            }
        }

        /// <remarks/>
        public string TAXJRSDCTN
        {
            get
            {
                return this.tAXJRSDCTNField;
            }
            set
            {
                this.tAXJRSDCTNField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TELEPHONE")]
        public TELEPHONE[] TELEPHONE
        {
            get
            {
                return this.tELEPHONEField;
            }
            set
            {
                this.tELEPHONEField = value;
            }
        }

        /// <remarks/>
        public string URL
        {
            get
            {
                return this.uRLField;
            }
            set
            {
                this.uRLField = value;
            }
        }

        /// <remarks/>
        public COLINX_ADDRESS_USERAREA COLINX_ADDRESS_USERAREA
        {
            get
            {
                return this.cOLINX_ADDRESS_USERAREAField;
            }
            set
            {
                this.cOLINX_ADDRESS_USERAREAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string returndata
        {
            get
            {
                return this.returndataField;
            }
            set
            {
                this.returndataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class CONTACT
    {

        private NAME nAMEField;

        private string cONTCTTYPEField;

        private string dESCRIPTNField;

        private string eMAILField;

        private FAX[] fAXField;

        private NAME[] nAME1Field;

        private TELEPHONE[] tELEPHONEField;

        private USERAREA uSERAREAField;

        private string returndataField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public NAME NAME
        {
            get
            {
                return this.nAMEField;
            }
            set
            {
                this.nAMEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string CONTCTTYPE
        {
            get
            {
                return this.cONTCTTYPEField;
            }
            set
            {
                this.cONTCTTYPEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string DESCRIPTN
        {
            get
            {
                return this.dESCRIPTNField;
            }
            set
            {
                this.dESCRIPTNField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string EMAIL
        {
            get
            {
                return this.eMAILField;
            }
            set
            {
                this.eMAILField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FAX", Order = 4)]
        public FAX[] FAX
        {
            get
            {
                return this.fAXField;
            }
            set
            {
                this.fAXField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NAME", Order = 5)]
        public NAME[] NAME1
        {
            get
            {
                return this.nAME1Field;
            }
            set
            {
                this.nAME1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TELEPHONE", Order = 6)]
        public TELEPHONE[] TELEPHONE
        {
            get
            {
                return this.tELEPHONEField;
            }
            set
            {
                this.tELEPHONEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public USERAREA USERAREA
        {
            get
            {
                return this.uSERAREAField;
            }
            set
            {
                this.uSERAREAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string returndata
        {
            get
            {
                return this.returndataField;
            }
            set
            {
                this.returndataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class PARTNER
    {

        private NAME nAMEField;

        private string oNETIMEField;

        private string pARTNRIDField;

        private string pARTNRTYPEField;

        private string sYNCINDField;

        private string aCTIVEField;

        private string cURRENCYField;

        private string dESCRIPTNField;

        private string dUNSNUMBERField;

        private string gLENTITYSField;

        private string pARENTIDField;

        private string pARTNRIDXField;

        private string pARTNRRATGField;

        private string pARTNRROLEField;

        private string pAYMETHODField;

        private string tAXEXEMPTField;

        private string tAXIDField;

        private string tERMIDField;

        private COLINX_PREFERENCE[] cOLINX_PARTNER_USERAREAField;

        private ADDRESS[] aDDRESSField;

        private CONTACT[] cONTACTField;

        private string returndataField;

        /// <remarks/>
        public NAME NAME
        {
            get
            {
                return this.nAMEField;
            }
            set
            {
                this.nAMEField = value;
            }
        }

        /// <remarks/>
        public string ONETIME
        {
            get
            {
                return this.oNETIMEField;
            }
            set
            {
                this.oNETIMEField = value;
            }
        }

        /// <remarks/>
        public string PARTNRID
        {
            get
            {
                return this.pARTNRIDField;
            }
            set
            {
                this.pARTNRIDField = value;
            }
        }

        /// <remarks/>
        public string PARTNRTYPE
        {
            get
            {
                return this.pARTNRTYPEField;
            }
            set
            {
                this.pARTNRTYPEField = value;
            }
        }

        /// <remarks/>
        public string SYNCIND
        {
            get
            {
                return this.sYNCINDField;
            }
            set
            {
                this.sYNCINDField = value;
            }
        }

        /// <remarks/>
        public string ACTIVE
        {
            get
            {
                return this.aCTIVEField;
            }
            set
            {
                this.aCTIVEField = value;
            }
        }

        /// <remarks/>
        public string CURRENCY
        {
            get
            {
                return this.cURRENCYField;
            }
            set
            {
                this.cURRENCYField = value;
            }
        }

        /// <remarks/>
        public string DESCRIPTN
        {
            get
            {
                return this.dESCRIPTNField;
            }
            set
            {
                this.dESCRIPTNField = value;
            }
        }

        /// <remarks/>
        public string DUNSNUMBER
        {
            get
            {
                return this.dUNSNUMBERField;
            }
            set
            {
                this.dUNSNUMBERField = value;
            }
        }

        /// <remarks/>
        public string GLENTITYS
        {
            get
            {
                return this.gLENTITYSField;
            }
            set
            {
                this.gLENTITYSField = value;
            }
        }

        /// <remarks/>
        public string PARENTID
        {
            get
            {
                return this.pARENTIDField;
            }
            set
            {
                this.pARENTIDField = value;
            }
        }

        /// <remarks/>
        public string PARTNRIDX
        {
            get
            {
                return this.pARTNRIDXField;
            }
            set
            {
                this.pARTNRIDXField = value;
            }
        }

        /// <remarks/>
        public string PARTNRRATG
        {
            get
            {
                return this.pARTNRRATGField;
            }
            set
            {
                this.pARTNRRATGField = value;
            }
        }

        /// <remarks/>
        public string PARTNRROLE
        {
            get
            {
                return this.pARTNRROLEField;
            }
            set
            {
                this.pARTNRROLEField = value;
            }
        }

        /// <remarks/>
        public string PAYMETHOD
        {
            get
            {
                return this.pAYMETHODField;
            }
            set
            {
                this.pAYMETHODField = value;
            }
        }

        /// <remarks/>
        public string TAXEXEMPT
        {
            get
            {
                return this.tAXEXEMPTField;
            }
            set
            {
                this.tAXEXEMPTField = value;
            }
        }

        /// <remarks/>
        public string TAXID
        {
            get
            {
                return this.tAXIDField;
            }
            set
            {
                this.tAXIDField = value;
            }
        }

        /// <remarks/>
        public string TERMID
        {
            get
            {
                return this.tERMIDField;
            }
            set
            {
                this.tERMIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("COLINX_PREFERENCE", IsNullable = false)]
        public COLINX_PREFERENCE[] COLINX_PARTNER_USERAREA
        {
            get
            {
                return this.cOLINX_PARTNER_USERAREAField;
            }
            set
            {
                this.cOLINX_PARTNER_USERAREAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADDRESS")]
        public ADDRESS[] ADDRESS
        {
            get
            {
                return this.aDDRESSField;
            }
            set
            {
                this.aDDRESSField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CONTACT")]
        public CONTACT[] CONTACT
        {
            get
            {
                return this.cONTACTField;
            }
            set
            {
                this.cONTACTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string returndata
        {
            get
            {
                return this.returndataField;
            }
            set
            {
                this.returndataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class PARTREF
    {

        private string pARTTYPEField;

        private string pARTNOField;

        private string pARTCLASSField;

        private string pARTKEYField;

        private string pARTQUALField;

        private string pARTDESCField;

        private string pRIORITYField;

        /// <remarks/>
        public string PARTTYPE
        {
            get
            {
                return this.pARTTYPEField;
            }
            set
            {
                this.pARTTYPEField = value;
            }
        }

        /// <remarks/>
        public string PARTNO
        {
            get
            {
                return this.pARTNOField;
            }
            set
            {
                this.pARTNOField = value;
            }
        }

        /// <remarks/>
        public string PARTCLASS
        {
            get
            {
                return this.pARTCLASSField;
            }
            set
            {
                this.pARTCLASSField = value;
            }
        }

        /// <remarks/>
        public string PARTKEY
        {
            get
            {
                return this.pARTKEYField;
            }
            set
            {
                this.pARTKEYField = value;
            }
        }

        /// <remarks/>
        public string PARTQUAL
        {
            get
            {
                return this.pARTQUALField;
            }
            set
            {
                this.pARTQUALField = value;
            }
        }

        /// <remarks/>
        public string PARTDESC
        {
            get
            {
                return this.pARTDESCField;
            }
            set
            {
                this.pARTDESCField = value;
            }
        }

        /// <remarks/>
        public string PRIORITY
        {
            get
            {
                return this.pRIORITYField;
            }
            set
            {
                this.pRIORITYField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class COLINX_QTEREF
    {

        private string qTEIDField;

        private string qTETYPEField;

        private string qTELINENUMField;

        private string qTESUBLINEField;

        /// <remarks/>
        public string QTEID
        {
            get
            {
                return this.qTEIDField;
            }
            set
            {
                this.qTEIDField = value;
            }
        }

        /// <remarks/>
        public string QTETYPE
        {
            get
            {
                return this.qTETYPEField;
            }
            set
            {
                this.qTETYPEField = value;
            }
        }

        /// <remarks/>
        public string QTELINENUM
        {
            get
            {
                return this.qTELINENUMField;
            }
            set
            {
                this.qTELINENUMField = value;
            }
        }

        /// <remarks/>
        public string QTESUBLINE
        {
            get
            {
                return this.qTESUBLINEField;
            }
            set
            {
                this.qTESUBLINEField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class COLINX_CCAUTH
    {

        private string cC_TYPEField;

        private string cC_NUMBERField;

        private string cC_VALID_TField;

        private string cC_NAMEField;

        /// <remarks/>
        public string CC_TYPE
        {
            get
            {
                return this.cC_TYPEField;
            }
            set
            {
                this.cC_TYPEField = value;
            }
        }

        /// <remarks/>
        public string CC_NUMBER
        {
            get
            {
                return this.cC_NUMBERField;
            }
            set
            {
                this.cC_NUMBERField = value;
            }
        }

        /// <remarks/>
        public string CC_VALID_T
        {
            get
            {
                return this.cC_VALID_TField;
            }
            set
            {
                this.cC_VALID_TField = value;
            }
        }

        /// <remarks/>
        public string CC_NAME
        {
            get
            {
                return this.cC_NAMEField;
            }
            set
            {
                this.cC_NAMEField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class COLINX_SHIPINSTR
    {

        private string cOLINX_ORDERTYPEField;

        private string cOLINX_FRTBILLTYPEField;

        private COLINX_CCAUTH cOLINX_CCAUTHField;

        private string cOLINX_DEVIATEFLGField;

        private string cOLINX_PARTSHIPField;

        private string cOLINX_FRTACCTNUMField;

        private string cOLINX_WICField;

        private string cOLINX_CONSOLFLGField;

        private string cOLINX_SHIPCMNTField;

        private string dESTCNTRYField;

        /// <remarks/>
        public string COLINX_ORDERTYPE
        {
            get
            {
                return this.cOLINX_ORDERTYPEField;
            }
            set
            {
                this.cOLINX_ORDERTYPEField = value;
            }
        }

        /// <remarks/>
        public string COLINX_FRTBILLTYPE
        {
            get
            {
                return this.cOLINX_FRTBILLTYPEField;
            }
            set
            {
                this.cOLINX_FRTBILLTYPEField = value;
            }
        }

        /// <remarks/>
        public COLINX_CCAUTH COLINX_CCAUTH
        {
            get
            {
                return this.cOLINX_CCAUTHField;
            }
            set
            {
                this.cOLINX_CCAUTHField = value;
            }
        }

        /// <remarks/>
        public string COLINX_DEVIATEFLG
        {
            get
            {
                return this.cOLINX_DEVIATEFLGField;
            }
            set
            {
                this.cOLINX_DEVIATEFLGField = value;
            }
        }

        /// <remarks/>
        public string COLINX_PARTSHIP
        {
            get
            {
                return this.cOLINX_PARTSHIPField;
            }
            set
            {
                this.cOLINX_PARTSHIPField = value;
            }
        }

        /// <remarks/>
        public string COLINX_FRTACCTNUM
        {
            get
            {
                return this.cOLINX_FRTACCTNUMField;
            }
            set
            {
                this.cOLINX_FRTACCTNUMField = value;
            }
        }

        /// <remarks/>
        public string COLINX_WIC
        {
            get
            {
                return this.cOLINX_WICField;
            }
            set
            {
                this.cOLINX_WICField = value;
            }
        }

        /// <remarks/>
        public string COLINX_CONSOLFLG
        {
            get
            {
                return this.cOLINX_CONSOLFLGField;
            }
            set
            {
                this.cOLINX_CONSOLFLGField = value;
            }
        }

        /// <remarks/>
        public string COLINX_SHIPCMNT
        {
            get
            {
                return this.cOLINX_SHIPCMNTField;
            }
            set
            {
                this.cOLINX_SHIPCMNTField = value;
            }
        }

        /// <remarks/>
        public string DESTCNTRY
        {
            get
            {
                return this.dESTCNTRYField;
            }
            set
            {
                this.dESTCNTRYField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class SPECIAL_INSTRUCTION
    {

        private string cODEField;

        private string dESCRIPTNField;

        /// <remarks/>
        public string CODE
        {
            get
            {
                return this.cODEField;
            }
            set
            {
                this.cODEField = value;
            }
        }

        /// <remarks/>
        public string DESCRIPTN
        {
            get
            {
                return this.dESCRIPTNField;
            }
            set
            {
                this.dESCRIPTNField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class SPECIAL_INSTRUCTIONS
    {

        private SPECIAL_INSTRUCTION[] sPECIAL_INSTRUCTIONField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SPECIAL_INSTRUCTION")]
        public SPECIAL_INSTRUCTION[] SPECIAL_INSTRUCTION
        {
            get
            {
                return this.sPECIAL_INSTRUCTIONField;
            }
            set
            {
                this.sPECIAL_INSTRUCTIONField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class GET_PRICELIST_002
    {

        private CNTROLAREA cNTROLAREAField;

        private DATAAREA[] dATAAREAField;

        /// <remarks/>
        public CNTROLAREA CNTROLAREA
        {
            get
            {
                return this.cNTROLAREAField;
            }
            set
            {
                this.cNTROLAREAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DATAAREA")]
        public DATAAREA[] DATAAREA
        {
            get
            {
                return this.dATAAREAField;
            }
            set
            {
                this.dATAAREAField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class DATAAREA
    {

        private GET_PRICELIST gET_PRICELISTField;

        /// <remarks/>
        public GET_PRICELIST GET_PRICELIST
        {
            get
            {
                return this.gET_PRICELISTField;
            }
            set
            {
                this.gET_PRICELISTField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class GET_PRICELIST
    {

        private PRICELIST pRICELISTField;

        /// <remarks/>
        public PRICELIST PRICELIST
        {
            get
            {
                return this.pRICELISTField;
            }
            set
            {
                this.pRICELISTField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class PRICELIST
    {

        private DATETIME dATETIMEField;

        private string pRICELSTIDField;

        private string pARTNRIDField;

        private string cURRENCYField;

        private string dESCRIPTNField;

        private string pRICELSTRVField;

        private PRICELIST_USERAREA pRICELIST_USERAREAField;

        private PARTNER[] pARTNERField;

        private PRCLSTLINE[] pRCLSTLINEField;

        private LISTPRCBRK[] lISTPRCBRKField;

        private PRCLSTQUAL[] pRCLSTQUALField;

        private string returndataField;

        /// <remarks/>
        public DATETIME DATETIME
        {
            get
            {
                return this.dATETIMEField;
            }
            set
            {
                this.dATETIMEField = value;
            }
        }

        /// <remarks/>
        public string PRICELSTID
        {
            get
            {
                return this.pRICELSTIDField;
            }
            set
            {
                this.pRICELSTIDField = value;
            }
        }

        /// <remarks/>
        public string PARTNRID
        {
            get
            {
                return this.pARTNRIDField;
            }
            set
            {
                this.pARTNRIDField = value;
            }
        }

        /// <remarks/>
        public string CURRENCY
        {
            get
            {
                return this.cURRENCYField;
            }
            set
            {
                this.cURRENCYField = value;
            }
        }

        /// <remarks/>
        public string DESCRIPTN
        {
            get
            {
                return this.dESCRIPTNField;
            }
            set
            {
                this.dESCRIPTNField = value;
            }
        }

        /// <remarks/>
        public string PRICELSTRV
        {
            get
            {
                return this.pRICELSTRVField;
            }
            set
            {
                this.pRICELSTRVField = value;
            }
        }

        /// <remarks/>
        public PRICELIST_USERAREA PRICELIST_USERAREA
        {
            get
            {
                return this.pRICELIST_USERAREAField;
            }
            set
            {
                this.pRICELIST_USERAREAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PARTNER")]
        public PARTNER[] PARTNER
        {
            get
            {
                return this.pARTNERField;
            }
            set
            {
                this.pARTNERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PRCLSTLINE")]
        public PRCLSTLINE[] PRCLSTLINE
        {
            get
            {
                return this.pRCLSTLINEField;
            }
            set
            {
                this.pRCLSTLINEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LISTPRCBRK")]
        public LISTPRCBRK[] LISTPRCBRK
        {
            get
            {
                return this.lISTPRCBRKField;
            }
            set
            {
                this.lISTPRCBRKField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PRCLSTQUAL")]
        public PRCLSTQUAL[] PRCLSTQUAL
        {
            get
            {
                return this.pRCLSTQUALField;
            }
            set
            {
                this.pRCLSTQUALField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string returndata
        {
            get
            {
                return this.returndataField;
            }
            set
            {
                this.returndataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class PRICELIST_USERAREA
    {

        private string qTEIDField;

        private string cOLINX_OEMNUMField;

        private string rEQUEST_FREIGHT_CHARGEField;

        private COLINX_SHIPINSTR cOLINX_SHIPINSTRField;

        /// <remarks/>
        public string QTEID
        {
            get
            {
                return this.qTEIDField;
            }
            set
            {
                this.qTEIDField = value;
            }
        }

        /// <remarks/>
        public string COLINX_OEMNUM
        {
            get
            {
                return this.cOLINX_OEMNUMField;
            }
            set
            {
                this.cOLINX_OEMNUMField = value;
            }
        }

        /// <remarks/>
        public string REQUEST_FREIGHT_CHARGE
        {
            get
            {
                return this.rEQUEST_FREIGHT_CHARGEField;
            }
            set
            {
                this.rEQUEST_FREIGHT_CHARGEField = value;
            }
        }

        /// <remarks/>
        public COLINX_SHIPINSTR COLINX_SHIPINSTR
        {
            get
            {
                return this.cOLINX_SHIPINSTRField;
            }
            set
            {
                this.cOLINX_SHIPINSTRField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class PRCLSTLINE
    {

        private OPERAMT oPERAMTField;

        private string dESCRIPTNField;

        private string lINENUMField;

        private PARTREF[] pARTREFField;

        private PRCLSTLINE_USERAREA pRCLSTLINE_USERAREAField;

        private LINEPRCBRK[] lINEPRCBRKField;

        private string returndataField;

        /// <remarks/>
        public OPERAMT OPERAMT
        {
            get
            {
                return this.oPERAMTField;
            }
            set
            {
                this.oPERAMTField = value;
            }
        }

        /// <remarks/>
        public string DESCRIPTN
        {
            get
            {
                return this.dESCRIPTNField;
            }
            set
            {
                this.dESCRIPTNField = value;
            }
        }

        /// <remarks/>
        public string LINENUM
        {
            get
            {
                return this.lINENUMField;
            }
            set
            {
                this.lINENUMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PARTREF")]
        public PARTREF[] PARTREF
        {
            get
            {
                return this.pARTREFField;
            }
            set
            {
                this.pARTREFField = value;
            }
        }

        /// <remarks/>
        public PRCLSTLINE_USERAREA PRCLSTLINE_USERAREA
        {
            get
            {
                return this.pRCLSTLINE_USERAREAField;
            }
            set
            {
                this.pRCLSTLINE_USERAREAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LINEPRCBRK")]
        public LINEPRCBRK[] LINEPRCBRK
        {
            get
            {
                return this.lINEPRCBRKField;
            }
            set
            {
                this.lINEPRCBRKField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string returndata
        {
            get
            {
                return this.returndataField;
            }
            set
            {
                this.returndataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class PRCLSTLINE_USERAREA
    {

        private DATETIME dATETIMEField;

        private QUANTITY qUANTITYField;

        private SITELEVEL sITELEVELField;

        private string pACKINGField;

        private string rEQUEST_SHIPMENT_OPTIONSField;

        private COLINX_QTEREF cOLINX_QTEREFField;

        private string pRICING_REFERENCEField;

        private string pRICING_UOMField;

        private SPECIAL_INSTRUCTION[] sPECIAL_INSTRUCTIONSField;

        /// <remarks/>
        public DATETIME DATETIME
        {
            get
            {
                return this.dATETIMEField;
            }
            set
            {
                this.dATETIMEField = value;
            }
        }

        /// <remarks/>
        public QUANTITY QUANTITY
        {
            get
            {
                return this.qUANTITYField;
            }
            set
            {
                this.qUANTITYField = value;
            }
        }

        /// <remarks/>
        public SITELEVEL SITELEVEL
        {
            get
            {
                return this.sITELEVELField;
            }
            set
            {
                this.sITELEVELField = value;
            }
        }

        /// <remarks/>
        public string PACKING
        {
            get
            {
                return this.pACKINGField;
            }
            set
            {
                this.pACKINGField = value;
            }
        }

        /// <remarks/>
        public string REQUEST_SHIPMENT_OPTIONS
        {
            get
            {
                return this.rEQUEST_SHIPMENT_OPTIONSField;
            }
            set
            {
                this.rEQUEST_SHIPMENT_OPTIONSField = value;
            }
        }

        /// <remarks/>
        public COLINX_QTEREF COLINX_QTEREF
        {
            get
            {
                return this.cOLINX_QTEREFField;
            }
            set
            {
                this.cOLINX_QTEREFField = value;
            }
        }

        /// <remarks/>
        public string PRICING_REFERENCE
        {
            get
            {
                return this.pRICING_REFERENCEField;
            }
            set
            {
                this.pRICING_REFERENCEField = value;
            }
        }

        /// <remarks/>
        public string PRICING_UOM
        {
            get
            {
                return this.pRICING_UOMField;
            }
            set
            {
                this.pRICING_UOMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SPECIAL_INSTRUCTION", IsNullable = false)]
        public SPECIAL_INSTRUCTION[] SPECIAL_INSTRUCTIONS
        {
            get
            {
                return this.sPECIAL_INSTRUCTIONSField;
            }
            set
            {
                this.sPECIAL_INSTRUCTIONSField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class LINEPRCBRK
    {

        private string dESCRIPTNField;

        private USERAREA uSERAREAField;

        private QUANTITY qUANTITYField;

        private AMOUNT aMOUNTField;

        private string oVERIDPRICField;

        private string returndataField;

        /// <remarks/>
        public string DESCRIPTN
        {
            get
            {
                return this.dESCRIPTNField;
            }
            set
            {
                this.dESCRIPTNField = value;
            }
        }

        /// <remarks/>
        public USERAREA USERAREA
        {
            get
            {
                return this.uSERAREAField;
            }
            set
            {
                this.uSERAREAField = value;
            }
        }

        /// <remarks/>
        public QUANTITY QUANTITY
        {
            get
            {
                return this.qUANTITYField;
            }
            set
            {
                this.qUANTITYField = value;
            }
        }

        /// <remarks/>
        public AMOUNT AMOUNT
        {
            get
            {
                return this.aMOUNTField;
            }
            set
            {
                this.aMOUNTField = value;
            }
        }

        /// <remarks/>
        public string OVERIDPRIC
        {
            get
            {
                return this.oVERIDPRICField;
            }
            set
            {
                this.oVERIDPRICField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string returndata
        {
            get
            {
                return this.returndataField;
            }
            set
            {
                this.returndataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class LISTPRCBRK
    {

        private AMOUNT[] aMOUNTField;

        private string dESCRIPTNField;

        private USERAREA uSERAREAField;

        private string returndataField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AMOUNT")]
        public AMOUNT[] AMOUNT
        {
            get
            {
                return this.aMOUNTField;
            }
            set
            {
                this.aMOUNTField = value;
            }
        }

        /// <remarks/>
        public string DESCRIPTN
        {
            get
            {
                return this.dESCRIPTNField;
            }
            set
            {
                this.dESCRIPTNField = value;
            }
        }

        /// <remarks/>
        public USERAREA USERAREA
        {
            get
            {
                return this.uSERAREAField;
            }
            set
            {
                this.uSERAREAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string returndata
        {
            get
            {
                return this.returndataField;
            }
            set
            {
                this.returndataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class PRCLSTQUAL
    {

        private string dESCRIPTNField;

        private SITELEVEL[] sITELEVELField;

        private USERAREA uSERAREAField;

        private string cATALGNAMEField;

        private string pARTNRIDField;

        private string returndataField;

        /// <remarks/>
        public string DESCRIPTN
        {
            get
            {
                return this.dESCRIPTNField;
            }
            set
            {
                this.dESCRIPTNField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SITELEVEL")]
        public SITELEVEL[] SITELEVEL
        {
            get
            {
                return this.sITELEVELField;
            }
            set
            {
                this.sITELEVELField = value;
            }
        }

        /// <remarks/>
        public USERAREA USERAREA
        {
            get
            {
                return this.uSERAREAField;
            }
            set
            {
                this.uSERAREAField = value;
            }
        }

        /// <remarks/>
        public string CATALGNAME
        {
            get
            {
                return this.cATALGNAMEField;
            }
            set
            {
                this.cATALGNAMEField = value;
            }
        }

        /// <remarks/>
        public string PARTNRID
        {
            get
            {
                return this.pARTNRIDField;
            }
            set
            {
                this.pARTNRIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string returndata
        {
            get
            {
                return this.returndataField;
            }
            set
            {
                this.returndataField = value;
            }
        }
    }
}