//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace WebService.asmx.showPriceList
{
    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class ELEMENT
    {

        private string indexField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class NOUN
    {

        private string valueField;

        private string valueField1;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField1;
            }
            set
            {
                this.valueField1 = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class REVISION
    {

        private string valueField;

        private string valueField1;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField1;
            }
            set
            {
                this.valueField1 = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class SITELEVEL
    {

        private string indexField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class USERAREA
    {

        private System.Xml.XmlNode[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class VERB
    {

        private string valueField;

        private string valueField1;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField1;
            }
            set
            {
                this.valueField1 = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class AMOUNT
    {

        private string vALUEField;

        private string nUMOFDECField;

        private string sIGNField;

        private string cURRENCYField;

        private string dRCRField;

        private AMOUNTQualifier qualifierField;

        private AMOUNTType typeField;

        private bool typeFieldSpecified;

        private string indexField;

        /// <remarks/>
        public string VALUE
        {
            get
            {
                return this.vALUEField;
            }
            set
            {
                this.vALUEField = value;
            }
        }

        /// <remarks/>
        public string NUMOFDEC
        {
            get
            {
                return this.nUMOFDECField;
            }
            set
            {
                this.nUMOFDECField = value;
            }
        }

        /// <remarks/>
        public string SIGN
        {
            get
            {
                return this.sIGNField;
            }
            set
            {
                this.sIGNField = value;
            }
        }

        /// <remarks/>
        public string CURRENCY
        {
            get
            {
                return this.cURRENCYField;
            }
            set
            {
                this.cURRENCYField = value;
            }
        }

        /// <remarks/>
        public string DRCR
        {
            get
            {
                return this.dRCRField;
            }
            set
            {
                this.dRCRField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AMOUNTQualifier qualifier
        {
            get
            {
                return this.qualifierField;
            }
            set
            {
                this.qualifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AMOUNTType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    public enum AMOUNTQualifier
    {

        /// <remarks/>
        ACTUAL,

        /// <remarks/>
        APPRVORD,

        /// <remarks/>
        AVAILABLE,

        /// <remarks/>
        BUDGET,

        /// <remarks/>
        COMMISSION,

        /// <remarks/>
        DECLAREVAL,

        /// <remarks/>
        DSCPRCNT,

        /// <remarks/>
        DSCVALUE,

        /// <remarks/>
        DISCNT,

        /// <remarks/>
        DOCUMENT,

        /// <remarks/>
        ESTENGIMP,

        /// <remarks/>
        ESTFREIGHT,

        /// <remarks/>
        ESTHRS,

        /// <remarks/>
        ESTIMATE,

        /// <remarks/>
        ESTMANIMP,

        /// <remarks/>
        ESTUCOST,

        /// <remarks/>
        EXTENDED,

        /// <remarks/>
        FREIGHT,

        /// <remarks/>
        ITEM,

        /// <remarks/>
        OPENITEM,

        /// <remarks/>
        ORDER,

        /// <remarks/>
        ORDLIMIT,

        /// <remarks/>
        PAYRATE,

        /// <remarks/>
        RATE,

        /// <remarks/>
        PRCBRK,

        /// <remarks/>
        TAX,

        /// <remarks/>
        TAXBASE,

        /// <remarks/>
        TOTAL,

        /// <remarks/>
        TOTLIMIT,

        /// <remarks/>
        OTHER,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("COLINX.DISCMULT")]
        COLINXDISCMULT,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    public enum AMOUNTType
    {

        /// <remarks/>
        T,

        /// <remarks/>
        F,

        /// <remarks/>
        OTHER,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class BSR
    {

        private VERB vERBField;

        private NOUN nOUNField;

        private REVISION rEVISIONField;

        /// <remarks/>
        public VERB VERB
        {
            get
            {
                return this.vERBField;
            }
            set
            {
                this.vERBField = value;
            }
        }

        /// <remarks/>
        public NOUN NOUN
        {
            get
            {
                return this.nOUNField;
            }
            set
            {
                this.nOUNField = value;
            }
        }

        /// <remarks/>
        public REVISION REVISION
        {
            get
            {
                return this.rEVISIONField;
            }
            set
            {
                this.rEVISIONField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class CNTROLAREA
    {

        private BSR bSRField;

        private SENDER sENDERField;

        private DATETIME dATETIMEField;

        /// <remarks/>
        public BSR BSR
        {
            get
            {
                return this.bSRField;
            }
            set
            {
                this.bSRField = value;
            }
        }

        /// <remarks/>
        public SENDER SENDER
        {
            get
            {
                return this.sENDERField;
            }
            set
            {
                this.sENDERField = value;
            }
        }

        /// <remarks/>
        public DATETIME DATETIME
        {
            get
            {
                return this.dATETIMEField;
            }
            set
            {
                this.dATETIMEField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class SENDER
    {

        private string lOGICALIDField;

        private string cOMPONENTField;

        private string tASKField;

        private string rEFERENCEIDField;

        private string cONFIRMATIONField;

        private string lANGUAGEField;

        private string cODEPAGEField;

        private string aUTHIDField;

        /// <remarks/>
        public string LOGICALID
        {
            get
            {
                return this.lOGICALIDField;
            }
            set
            {
                this.lOGICALIDField = value;
            }
        }

        /// <remarks/>
        public string COMPONENT
        {
            get
            {
                return this.cOMPONENTField;
            }
            set
            {
                this.cOMPONENTField = value;
            }
        }

        /// <remarks/>
        public string TASK
        {
            get
            {
                return this.tASKField;
            }
            set
            {
                this.tASKField = value;
            }
        }

        /// <remarks/>
        public string REFERENCEID
        {
            get
            {
                return this.rEFERENCEIDField;
            }
            set
            {
                this.rEFERENCEIDField = value;
            }
        }

        /// <remarks/>
        public string CONFIRMATION
        {
            get
            {
                return this.cONFIRMATIONField;
            }
            set
            {
                this.cONFIRMATIONField = value;
            }
        }

        /// <remarks/>
        public string LANGUAGE
        {
            get
            {
                return this.lANGUAGEField;
            }
            set
            {
                this.lANGUAGEField = value;
            }
        }

        /// <remarks/>
        public string CODEPAGE
        {
            get
            {
                return this.cODEPAGEField;
            }
            set
            {
                this.cODEPAGEField = value;
            }
        }

        /// <remarks/>
        public string AUTHID
        {
            get
            {
                return this.aUTHIDField;
            }
            set
            {
                this.aUTHIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class DATETIME
    {

        private string yEARField;

        private string mONTHField;

        private string dAYField;

        private string hOURField;

        private string mINUTEField;

        private string sECONDField;

        private string sUBSECONDField;

        private string tIMEZONEField;

        private DATETIMEQualifier qualifierField;

        private DATETIMEType typeField;

        private bool typeFieldSpecified;

        private string indexField;

        /// <remarks/>
        public string YEAR
        {
            get
            {
                return this.yEARField;
            }
            set
            {
                this.yEARField = value;
            }
        }

        /// <remarks/>
        public string MONTH
        {
            get
            {
                return this.mONTHField;
            }
            set
            {
                this.mONTHField = value;
            }
        }

        /// <remarks/>
        public string DAY
        {
            get
            {
                return this.dAYField;
            }
            set
            {
                this.dAYField = value;
            }
        }

        /// <remarks/>
        public string HOUR
        {
            get
            {
                return this.hOURField;
            }
            set
            {
                this.hOURField = value;
            }
        }

        /// <remarks/>
        public string MINUTE
        {
            get
            {
                return this.mINUTEField;
            }
            set
            {
                this.mINUTEField = value;
            }
        }

        /// <remarks/>
        public string SECOND
        {
            get
            {
                return this.sECONDField;
            }
            set
            {
                this.sECONDField = value;
            }
        }

        /// <remarks/>
        public string SUBSECOND
        {
            get
            {
                return this.sUBSECONDField;
            }
            set
            {
                this.sUBSECONDField = value;
            }
        }

        /// <remarks/>
        public string TIMEZONE
        {
            get
            {
                return this.tIMEZONEField;
            }
            set
            {
                this.tIMEZONEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DATETIMEQualifier qualifier
        {
            get
            {
                return this.qualifierField;
            }
            set
            {
                this.qualifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DATETIMEType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    public enum DATETIMEQualifier
    {

        /// <remarks/>
        ACCOUNTING,

        /// <remarks/>
        ACTEND,

        /// <remarks/>
        ACTSTART,

        /// <remarks/>
        APPREQ,

        /// <remarks/>
        APPROVAL,

        /// <remarks/>
        AVAILABLE,

        /// <remarks/>
        BKTEND,

        /// <remarks/>
        BKTSTART,

        /// <remarks/>
        CANCEL,

        /// <remarks/>
        CHANGEDATE,

        /// <remarks/>
        COMPDATE,

        /// <remarks/>
        CREATION,

        /// <remarks/>
        CUMULATIVE,

        /// <remarks/>
        DELIVACT,

        /// <remarks/>
        DELIVSCHED,

        /// <remarks/>
        DISCNT,

        /// <remarks/>
        DOCUMENT,

        /// <remarks/>
        DUE,

        /// <remarks/>
        EARLSTEFF,

        /// <remarks/>
        EARLSTSHIP,

        /// <remarks/>
        EFFECTIVE,

        /// <remarks/>
        ENGCHG,

        /// <remarks/>
        EXECFINISH,

        /// <remarks/>
        EXECSTART,

        /// <remarks/>
        EXPIRATION,

        /// <remarks/>
        FAILDATE,

        /// <remarks/>
        FORECASTF,

        /// <remarks/>
        FORECASTS,

        /// <remarks/>
        FROM,

        /// <remarks/>
        GENERATION,

        /// <remarks/>
        IMPL,

        /// <remarks/>
        INVOICE,

        /// <remarks/>
        LABORFINSH,

        /// <remarks/>
        LABORSTART,

        /// <remarks/>
        LASTUSED,

        /// <remarks/>
        LOADING,

        /// <remarks/>
        MATCHING,

        /// <remarks/>
        MSMENTDATE,

        /// <remarks/>
        NEEDDELV,

        /// <remarks/>
        OPFINISH,

        /// <remarks/>
        OPSTART,

        /// <remarks/>
        PAYEND,

        /// <remarks/>
        PLANEND,

        /// <remarks/>
        PLANSTART,

        /// <remarks/>
        PO,

        /// <remarks/>
        PROMDELV,

        /// <remarks/>
        PROMSHIP,

        /// <remarks/>
        PYMTTERM,

        /// <remarks/>
        RECEIVED,

        /// <remarks/>
        REPORTDATE,

        /// <remarks/>
        REPORTNGFN,

        /// <remarks/>
        REPORTNGST,

        /// <remarks/>
        REQUIRED,

        /// <remarks/>
        RESORCDWNF,

        /// <remarks/>
        RESORCDWNS,

        /// <remarks/>
        RSPDDATE,

        /// <remarks/>
        RSPDOCGEN,

        /// <remarks/>
        SCHEND,

        /// <remarks/>
        SCHSTART,

        /// <remarks/>
        SETUPFINSH,

        /// <remarks/>
        SETUPSTART,

        /// <remarks/>
        SHIP,

        /// <remarks/>
        SHIPSCHED,

        /// <remarks/>
        STATUSDATE,

        /// <remarks/>
        TEARDOWNF,

        /// <remarks/>
        TEARDOWNS,

        /// <remarks/>
        TO,

        /// <remarks/>
        OTHER,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("COLINX.CARDEXP")]
        COLINXCARDEXP,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("COLINX.REQUESTED")]
        COLINXREQUESTED,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    public enum DATETIMEType
    {

        /// <remarks/>
        T,

        /// <remarks/>
        F,

        /// <remarks/>
        OTHER,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class OPERAMT
    {

        private string vALUEField;

        private string nUMOFDECField;

        private string sIGNField;

        private string cURRENCYField;

        private string dRCRField;

        private string uOMVALUEField;

        private string uOMNUMDECField;

        private string uOMField;

        private OPERAMTQualifier qualifierField;

        private OPERAMTType typeField;

        /// <remarks/>
        public string VALUE
        {
            get
            {
                return this.vALUEField;
            }
            set
            {
                this.vALUEField = value;
            }
        }

        /// <remarks/>
        public string NUMOFDEC
        {
            get
            {
                return this.nUMOFDECField;
            }
            set
            {
                this.nUMOFDECField = value;
            }
        }

        /// <remarks/>
        public string SIGN
        {
            get
            {
                return this.sIGNField;
            }
            set
            {
                this.sIGNField = value;
            }
        }

        /// <remarks/>
        public string CURRENCY
        {
            get
            {
                return this.cURRENCYField;
            }
            set
            {
                this.cURRENCYField = value;
            }
        }

        /// <remarks/>
        public string DRCR
        {
            get
            {
                return this.dRCRField;
            }
            set
            {
                this.dRCRField = value;
            }
        }

        /// <remarks/>
        public string UOMVALUE
        {
            get
            {
                return this.uOMVALUEField;
            }
            set
            {
                this.uOMVALUEField = value;
            }
        }

        /// <remarks/>
        public string UOMNUMDEC
        {
            get
            {
                return this.uOMNUMDECField;
            }
            set
            {
                this.uOMNUMDECField = value;
            }
        }

        /// <remarks/>
        public string UOM
        {
            get
            {
                return this.uOMField;
            }
            set
            {
                this.uOMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public OPERAMTQualifier qualifier
        {
            get
            {
                return this.qualifierField;
            }
            set
            {
                this.qualifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public OPERAMTType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    public enum OPERAMTQualifier
    {

        /// <remarks/>
        COST,

        /// <remarks/>
        EXTENDED,

        /// <remarks/>
        EXTENDED_INCL_TAX,

        /// <remarks/>
        FREIGHT,

        /// <remarks/>
        UNIT,

        /// <remarks/>
        OTHER,

        /// <remarks/>
        LPRICE,

        /// <remarks/>
        RVPRICE,

        /// <remarks/>
        SHIPPING,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    public enum OPERAMTType
    {

        /// <remarks/>
        T,

        /// <remarks/>
        F,

        /// <remarks/>
        OTHER,

        /// <remarks/>
        LPRICE,

        /// <remarks/>
        RVPRICE,

        /// <remarks/>
        S,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class QUANTITY
    {

        private string vALUEField;

        private string nUMOFDECField;

        private string sIGNField;

        private string uOMField;

        private QUANTITYQualifier qualifierField;

        /// <remarks/>
        public string VALUE
        {
            get
            {
                return this.vALUEField;
            }
            set
            {
                this.vALUEField = value;
            }
        }

        /// <remarks/>
        public string NUMOFDEC
        {
            get
            {
                return this.nUMOFDECField;
            }
            set
            {
                this.nUMOFDECField = value;
            }
        }

        /// <remarks/>
        public string SIGN
        {
            get
            {
                return this.sIGNField;
            }
            set
            {
                this.sIGNField = value;
            }
        }

        /// <remarks/>
        public string UOM
        {
            get
            {
                return this.uOMField;
            }
            set
            {
                this.uOMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public QUANTITYQualifier qualifier
        {
            get
            {
                return this.qualifierField;
            }
            set
            {
                this.qualifierField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    public enum QUANTITYQualifier
    {

        /// <remarks/>
        ACCEPTED,

        /// <remarks/>
        ACTDUR,

        /// <remarks/>
        ACTHRS,

        /// <remarks/>
        ALLOCATED,

        /// <remarks/>
        ALLOWEDWT,

        /// <remarks/>
        AVAILABLE,

        /// <remarks/>
        AVGRUNSIZE,

        /// <remarks/>
        BACKORDERD,

        /// <remarks/>
        BATCHSIZE,

        /// <remarks/>
        BATCHTIME,

        /// <remarks/>
        BLOCKED,

        /// <remarks/>
        BREAKTIME,

        /// <remarks/>
        CAPPERCENT,

        /// <remarks/>
        CATCHWEGHT,

        /// <remarks/>
        COMMISSION,

        /// <remarks/>
        COMPLETED,

        /// <remarks/>
        CUMULATIVE,

        /// <remarks/>
        DELIVERED,

        /// <remarks/>
        DURATION,

        /// <remarks/>
        DUROVER,

        /// <remarks/>
        DURUNDER,

        /// <remarks/>
        EMPLOYEES,

        /// <remarks/>
        EMPREQD,

        /// <remarks/>
        ESTDUR,

        /// <remarks/>
        ESTHRS,

        /// <remarks/>
        ESTWEIGHT,

        /// <remarks/>
        FILENAME,

        /// <remarks/>
        FILESIZE,

        /// <remarks/>
        FIXEDTIME,

        /// <remarks/>
        HEIGHT,

        /// <remarks/>
        INSPECTED,

        /// <remarks/>
        INSPECTION,

        /// <remarks/>
        ITEM,

        /// <remarks/>
        LDTMOFFSET,

        /// <remarks/>
        LENGTH,

        /// <remarks/>
        LABOR,

        /// <remarks/>
        LOADINGWT,

        /// <remarks/>
        LOTSIZEMAX,

        /// <remarks/>
        LOTSIZEMIN,

        /// <remarks/>
        LOTSIZEMLT,

        /// <remarks/>
        LOWERLIMIT,

        /// <remarks/>
        MACHINEHRS,

        /// <remarks/>
        MAXIMUM,

        /// <remarks/>
        MAXPARLTM,

        /// <remarks/>
        MINIMUM,

        /// <remarks/>
        MOVETIME,

        /// <remarks/>
        MSMENT,

        /// <remarks/>
        MULTIPLIER,

        /// <remarks/>
        NETWEIGHT,

        /// <remarks/>
        OPEN,

        /// <remarks/>
        ORDERED,

        /// <remarks/>
        OTHERREJ,

        /// <remarks/>
        OVERSHIP,

        /// <remarks/>
        PACKING,

        /// <remarks/>
        PERCENT,

        /// <remarks/>
        PERCENTREQ,

        /// <remarks/>
        PERSHBNOPR,

        /// <remarks/>
        PERSHWIOPR,

        /// <remarks/>
        PLNDPRCT,

        /// <remarks/>
        PRCBRK,

        /// <remarks/>
        PRIOR,

        /// <remarks/>
        QUEUETIME,

        /// <remarks/>
        RATE,

        /// <remarks/>
        RECEIVED,

        /// <remarks/>
        REJECTED,

        /// <remarks/>
        REJPERCENT,

        /// <remarks/>
        REMDUR,

        /// <remarks/>
        REMHRS,

        /// <remarks/>
        REQUIRED,

        /// <remarks/>
        RETURNED,

        /// <remarks/>
        REWORK,

        /// <remarks/>
        RUNTIME,

        /// <remarks/>
        SCRAP,

        /// <remarks/>
        SETUPTIME,

        /// <remarks/>
        SHELFLIFE,

        /// <remarks/>
        SHIPPED,

        /// <remarks/>
        SHIPUNIT,

        /// <remarks/>
        TEARDOWN,

        /// <remarks/>
        TOOLREQD,

        /// <remarks/>
        TOTWEIGHT,

        /// <remarks/>
        TRANSFRLOT,

        /// <remarks/>
        UNDERSHIP,

        /// <remarks/>
        UNIT,

        /// <remarks/>
        UPPERLIMIT,

        /// <remarks/>
        VOLUME,

        /// <remarks/>
        WAITTIME,

        /// <remarks/>
        WEIGHT,

        /// <remarks/>
        WIDTH,

        /// <remarks/>
        OTHER,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("COLINX.TOTWEIGHT")]
        COLINXTOTWEIGHT,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("COLINX.ALLOWED")]
        COLINXALLOWED,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("COLINX.ORDERED")]
        COLINXORDERED,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("COLINX.REMAIN")]
        COLINXREMAIN,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class DISTRIBUTN
    {

        private OPERAMT oPERAMTField;

        private string bUSNAREAField;

        private string cOSTCENTERField;

        private string dEPARTMENTField;

        private string dIVISIONField;

        private ELEMENT[] eLEMENTField;

        private string fUNDField;

        private string gEOGRAPHYField;

        private string gLENTITYSField;

        private string gLNOMACCTField;

        private string pROFITCTRField;

        private string pROJECTField;

        private string uNITField;

        private string wAREHOUSEField;

        private USERAREA uSERAREAField;

        private string returndataField;

        /// <remarks/>
        public OPERAMT OPERAMT
        {
            get
            {
                return this.oPERAMTField;
            }
            set
            {
                this.oPERAMTField = value;
            }
        }

        /// <remarks/>
        public string BUSNAREA
        {
            get
            {
                return this.bUSNAREAField;
            }
            set
            {
                this.bUSNAREAField = value;
            }
        }

        /// <remarks/>
        public string COSTCENTER
        {
            get
            {
                return this.cOSTCENTERField;
            }
            set
            {
                this.cOSTCENTERField = value;
            }
        }

        /// <remarks/>
        public string DEPARTMENT
        {
            get
            {
                return this.dEPARTMENTField;
            }
            set
            {
                this.dEPARTMENTField = value;
            }
        }

        /// <remarks/>
        public string DIVISION
        {
            get
            {
                return this.dIVISIONField;
            }
            set
            {
                this.dIVISIONField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ELEMENT")]
        public ELEMENT[] ELEMENT
        {
            get
            {
                return this.eLEMENTField;
            }
            set
            {
                this.eLEMENTField = value;
            }
        }

        /// <remarks/>
        public string FUND
        {
            get
            {
                return this.fUNDField;
            }
            set
            {
                this.fUNDField = value;
            }
        }

        /// <remarks/>
        public string GEOGRAPHY
        {
            get
            {
                return this.gEOGRAPHYField;
            }
            set
            {
                this.gEOGRAPHYField = value;
            }
        }

        /// <remarks/>
        public string GLENTITYS
        {
            get
            {
                return this.gLENTITYSField;
            }
            set
            {
                this.gLENTITYSField = value;
            }
        }

        /// <remarks/>
        public string GLNOMACCT
        {
            get
            {
                return this.gLNOMACCTField;
            }
            set
            {
                this.gLNOMACCTField = value;
            }
        }

        /// <remarks/>
        public string PROFITCTR
        {
            get
            {
                return this.pROFITCTRField;
            }
            set
            {
                this.pROFITCTRField = value;
            }
        }

        /// <remarks/>
        public string PROJECT
        {
            get
            {
                return this.pROJECTField;
            }
            set
            {
                this.pROJECTField = value;
            }
        }

        /// <remarks/>
        public string UNIT
        {
            get
            {
                return this.uNITField;
            }
            set
            {
                this.uNITField = value;
            }
        }

        /// <remarks/>
        public string WAREHOUSE
        {
            get
            {
                return this.wAREHOUSEField;
            }
            set
            {
                this.wAREHOUSEField = value;
            }
        }

        /// <remarks/>
        public USERAREA USERAREA
        {
            get
            {
                return this.uSERAREAField;
            }
            set
            {
                this.uSERAREAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string returndata
        {
            get
            {
                return this.returndataField;
            }
            set
            {
                this.returndataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class CHARGE
    {

        private OPERAMT oPERAMTField;

        private string cHARGEIDField;

        private string cHARGETYPEField;

        private string cHGLINENUMField;

        private string dESCRIPTNField;

        private USERAREA uSERAREAField;

        private DISTRIBUTN[] dISTRIBUTNField;

        private string returndataField;

        /// <remarks/>
        public OPERAMT OPERAMT
        {
            get
            {
                return this.oPERAMTField;
            }
            set
            {
                this.oPERAMTField = value;
            }
        }

        /// <remarks/>
        public string CHARGEID
        {
            get
            {
                return this.cHARGEIDField;
            }
            set
            {
                this.cHARGEIDField = value;
            }
        }

        /// <remarks/>
        public string CHARGETYPE
        {
            get
            {
                return this.cHARGETYPEField;
            }
            set
            {
                this.cHARGETYPEField = value;
            }
        }

        /// <remarks/>
        public string CHGLINENUM
        {
            get
            {
                return this.cHGLINENUMField;
            }
            set
            {
                this.cHGLINENUMField = value;
            }
        }

        /// <remarks/>
        public string DESCRIPTN
        {
            get
            {
                return this.dESCRIPTNField;
            }
            set
            {
                this.dESCRIPTNField = value;
            }
        }

        /// <remarks/>
        public USERAREA USERAREA
        {
            get
            {
                return this.uSERAREAField;
            }
            set
            {
                this.uSERAREAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DISTRIBUTN")]
        public DISTRIBUTN[] DISTRIBUTN
        {
            get
            {
                return this.dISTRIBUTNField;
            }
            set
            {
                this.dISTRIBUTNField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string returndata
        {
            get
            {
                return this.returndataField;
            }
            set
            {
                this.returndataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class COLINX_QTEREF
    {

        private string qTEIDField;

        private string qTETYPEField;

        private string qTELINENUMField;

        private string qTESUBLINEField;

        /// <remarks/>
        public string QTEID
        {
            get
            {
                return this.qTEIDField;
            }
            set
            {
                this.qTEIDField = value;
            }
        }

        /// <remarks/>
        public string QTETYPE
        {
            get
            {
                return this.qTETYPEField;
            }
            set
            {
                this.qTETYPEField = value;
            }
        }

        /// <remarks/>
        public string QTELINENUM
        {
            get
            {
                return this.qTELINENUMField;
            }
            set
            {
                this.qTELINENUMField = value;
            }
        }

        /// <remarks/>
        public string QTESUBLINE
        {
            get
            {
                return this.qTESUBLINEField;
            }
            set
            {
                this.qTESUBLINEField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class COLINX_STATUS
    {

        private string rEASONCODEField;

        private string dESCRIPTNField;

        /// <remarks/>
        public string REASONCODE
        {
            get
            {
                return this.rEASONCODEField;
            }
            set
            {
                this.rEASONCODEField = value;
            }
        }

        /// <remarks/>
        public string DESCRIPTN
        {
            get
            {
                return this.dESCRIPTNField;
            }
            set
            {
                this.dESCRIPTNField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class COLINX_CCAUTH
    {

        private string cC_TYPEField;

        private string cC_NUMBERField;

        private string cC_VALID_TField;

        private string cC_NAMEField;

        /// <remarks/>
        public string CC_TYPE
        {
            get
            {
                return this.cC_TYPEField;
            }
            set
            {
                this.cC_TYPEField = value;
            }
        }

        /// <remarks/>
        public string CC_NUMBER
        {
            get
            {
                return this.cC_NUMBERField;
            }
            set
            {
                this.cC_NUMBERField = value;
            }
        }

        /// <remarks/>
        public string CC_VALID_T
        {
            get
            {
                return this.cC_VALID_TField;
            }
            set
            {
                this.cC_VALID_TField = value;
            }
        }

        /// <remarks/>
        public string CC_NAME
        {
            get
            {
                return this.cC_NAMEField;
            }
            set
            {
                this.cC_NAMEField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class COLINX_SHIPINSTR
    {

        private string cOLINX_ORDERTYPEField;

        private string cOLINX_FRTBILLTYPEField;

        private COLINX_CCAUTH cOLINX_CCAUTHField;

        private string cOLINX_DEVIATEFLGField;

        private string cOLINX_PARTSHIPField;

        private string cOLINX_FRTACCTNUMField;

        private string cOLINX_WICField;

        private string cOLINX_CONSOLFLGField;

        private string cOLINX_SHIPCMNTField;

        private string dESTCNTRYField;

        /// <remarks/>
        public string COLINX_ORDERTYPE
        {
            get
            {
                return this.cOLINX_ORDERTYPEField;
            }
            set
            {
                this.cOLINX_ORDERTYPEField = value;
            }
        }

        /// <remarks/>
        public string COLINX_FRTBILLTYPE
        {
            get
            {
                return this.cOLINX_FRTBILLTYPEField;
            }
            set
            {
                this.cOLINX_FRTBILLTYPEField = value;
            }
        }

        /// <remarks/>
        public COLINX_CCAUTH COLINX_CCAUTH
        {
            get
            {
                return this.cOLINX_CCAUTHField;
            }
            set
            {
                this.cOLINX_CCAUTHField = value;
            }
        }

        /// <remarks/>
        public string COLINX_DEVIATEFLG
        {
            get
            {
                return this.cOLINX_DEVIATEFLGField;
            }
            set
            {
                this.cOLINX_DEVIATEFLGField = value;
            }
        }

        /// <remarks/>
        public string COLINX_PARTSHIP
        {
            get
            {
                return this.cOLINX_PARTSHIPField;
            }
            set
            {
                this.cOLINX_PARTSHIPField = value;
            }
        }

        /// <remarks/>
        public string COLINX_FRTACCTNUM
        {
            get
            {
                return this.cOLINX_FRTACCTNUMField;
            }
            set
            {
                this.cOLINX_FRTACCTNUMField = value;
            }
        }

        /// <remarks/>
        public string COLINX_WIC
        {
            get
            {
                return this.cOLINX_WICField;
            }
            set
            {
                this.cOLINX_WICField = value;
            }
        }

        /// <remarks/>
        public string COLINX_CONSOLFLG
        {
            get
            {
                return this.cOLINX_CONSOLFLGField;
            }
            set
            {
                this.cOLINX_CONSOLFLGField = value;
            }
        }

        /// <remarks/>
        public string COLINX_SHIPCMNT
        {
            get
            {
                return this.cOLINX_SHIPCMNTField;
            }
            set
            {
                this.cOLINX_SHIPCMNTField = value;
            }
        }

        /// <remarks/>
        public string DESTCNTRY
        {
            get
            {
                return this.dESTCNTRYField;
            }
            set
            {
                this.dESTCNTRYField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class LEAD_TIME
    {

        private string uOMField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UOM
        {
            get
            {
                return this.uOMField;
            }
            set
            {
                this.uOMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class WHSEDETAIL
    {

        private QUANTITY qUANTITYField;

        private object itemField;

        private SITELEVEL sITELEVELField;

        private string oRDERABLEField;

        private string pRODORDIDField;

        private string pRIORITYField;

        private string pRDLINENUMField;

        private string cOLINX_SORTORDERField;

        private string dEFAULTINDField;

        /// <remarks/>
        public QUANTITY QUANTITY
        {
            get
            {
                return this.qUANTITYField;
            }
            set
            {
                this.qUANTITYField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("COLINX_AVAILDESC", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("DATETIME", typeof(DATETIME))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        public SITELEVEL SITELEVEL
        {
            get
            {
                return this.sITELEVELField;
            }
            set
            {
                this.sITELEVELField = value;
            }
        }

        /// <remarks/>
        public string ORDERABLE
        {
            get
            {
                return this.oRDERABLEField;
            }
            set
            {
                this.oRDERABLEField = value;
            }
        }

        /// <remarks/>
        public string PRODORDID
        {
            get
            {
                return this.pRODORDIDField;
            }
            set
            {
                this.pRODORDIDField = value;
            }
        }

        /// <remarks/>
        public string PRIORITY
        {
            get
            {
                return this.pRIORITYField;
            }
            set
            {
                this.pRIORITYField = value;
            }
        }

        /// <remarks/>
        public string PRDLINENUM
        {
            get
            {
                return this.pRDLINENUMField;
            }
            set
            {
                this.pRDLINENUMField = value;
            }
        }

        /// <remarks/>
        public string COLINX_SORTORDER
        {
            get
            {
                return this.cOLINX_SORTORDERField;
            }
            set
            {
                this.cOLINX_SORTORDERField = value;
            }
        }

        /// <remarks/>
        public string DEFAULTIND
        {
            get
            {
                return this.dEFAULTINDField;
            }
            set
            {
                this.dEFAULTINDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class PARTREF
    {

        private string pARTTYPEField;

        private string pARTNOField;

        private string pARTCLASSField;

        private string pARTKEYField;

        private string pARTQUALField;

        private string pARTDESCField;

        private string pRIORITYField;

        /// <remarks/>
        public string PARTTYPE
        {
            get
            {
                return this.pARTTYPEField;
            }
            set
            {
                this.pARTTYPEField = value;
            }
        }

        /// <remarks/>
        public string PARTNO
        {
            get
            {
                return this.pARTNOField;
            }
            set
            {
                this.pARTNOField = value;
            }
        }

        /// <remarks/>
        public string PARTCLASS
        {
            get
            {
                return this.pARTCLASSField;
            }
            set
            {
                this.pARTCLASSField = value;
            }
        }

        /// <remarks/>
        public string PARTKEY
        {
            get
            {
                return this.pARTKEYField;
            }
            set
            {
                this.pARTKEYField = value;
            }
        }

        /// <remarks/>
        public string PARTQUAL
        {
            get
            {
                return this.pARTQUALField;
            }
            set
            {
                this.pARTQUALField = value;
            }
        }

        /// <remarks/>
        public string PARTDESC
        {
            get
            {
                return this.pARTDESCField;
            }
            set
            {
                this.pARTDESCField = value;
            }
        }

        /// <remarks/>
        public string PRIORITY
        {
            get
            {
                return this.pRIORITYField;
            }
            set
            {
                this.pRIORITYField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class COLINX_PRODAVAIL
    {

        private string dEFAULTINDField;

        private string cOLINX_SORTORDERField;

        private string pACKINGField;

        private OPERAMT oPERAMTField;

        private QUANTITY[] qUANTITYField;

        private WHSEDETAIL[] wHSEDETAILField;

        /// <remarks/>
        public string DEFAULTIND
        {
            get
            {
                return this.dEFAULTINDField;
            }
            set
            {
                this.dEFAULTINDField = value;
            }
        }

        /// <remarks/>
        public string COLINX_SORTORDER
        {
            get
            {
                return this.cOLINX_SORTORDERField;
            }
            set
            {
                this.cOLINX_SORTORDERField = value;
            }
        }

        /// <remarks/>
        public string PACKING
        {
            get
            {
                return this.pACKINGField;
            }
            set
            {
                this.pACKINGField = value;
            }
        }

        /// <remarks/>
        public OPERAMT OPERAMT
        {
            get
            {
                return this.oPERAMTField;
            }
            set
            {
                this.oPERAMTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("QUANTITY")]
        public QUANTITY[] QUANTITY
        {
            get
            {
                return this.qUANTITYField;
            }
            set
            {
                this.qUANTITYField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WHSEDETAIL")]
        public WHSEDETAIL[] WHSEDETAIL
        {
            get
            {
                return this.wHSEDETAILField;
            }
            set
            {
                this.wHSEDETAILField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class MANUFACTURE
    {

        private LEAD_TIME lEAD_TIMEField;

        private string mATERIALField;

        private string pLANTField;

        private string tYPEField;

        /// <remarks/>
        public LEAD_TIME LEAD_TIME
        {
            get
            {
                return this.lEAD_TIMEField;
            }
            set
            {
                this.lEAD_TIMEField = value;
            }
        }

        /// <remarks/>
        public string MATERIAL
        {
            get
            {
                return this.mATERIALField;
            }
            set
            {
                this.mATERIALField = value;
            }
        }

        /// <remarks/>
        public string PLANT
        {
            get
            {
                return this.pLANTField;
            }
            set
            {
                this.pLANTField = value;
            }
        }

        /// <remarks/>
        public string TYPE
        {
            get
            {
                return this.tYPEField;
            }
            set
            {
                this.tYPEField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class SPECIAL_INSTRUCTION
    {

        private string cODEField;

        private string dESCRIPTNField;

        /// <remarks/>
        public string CODE
        {
            get
            {
                return this.cODEField;
            }
            set
            {
                this.cODEField = value;
            }
        }

        /// <remarks/>
        public string DESCRIPTN
        {
            get
            {
                return this.dESCRIPTNField;
            }
            set
            {
                this.dESCRIPTNField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class SPECIAL_INSTRUCTIONS
    {

        private SPECIAL_INSTRUCTION[] sPECIAL_INSTRUCTIONField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SPECIAL_INSTRUCTION")]
        public SPECIAL_INSTRUCTION[] SPECIAL_INSTRUCTION
        {
            get
            {
                return this.sPECIAL_INSTRUCTIONField;
            }
            set
            {
                this.sPECIAL_INSTRUCTIONField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class SHIPMENT_OPTION
    {

        private string sORT_ORDERField;

        private string lIMIT_ORDERABLE_QUANTITYField;

        private SITELEVEL sITELEVELField;

        private string sHIPMENT_GROUPField;

        private CHARGE cHARGEField;

        /// <remarks/>
        public string SORT_ORDER
        {
            get
            {
                return this.sORT_ORDERField;
            }
            set
            {
                this.sORT_ORDERField = value;
            }
        }

        /// <remarks/>
        public string LIMIT_ORDERABLE_QUANTITY
        {
            get
            {
                return this.lIMIT_ORDERABLE_QUANTITYField;
            }
            set
            {
                this.lIMIT_ORDERABLE_QUANTITYField = value;
            }
        }

        /// <remarks/>
        public SITELEVEL SITELEVEL
        {
            get
            {
                return this.sITELEVELField;
            }
            set
            {
                this.sITELEVELField = value;
            }
        }

        /// <remarks/>
        public string SHIPMENT_GROUP
        {
            get
            {
                return this.sHIPMENT_GROUPField;
            }
            set
            {
                this.sHIPMENT_GROUPField = value;
            }
        }

        /// <remarks/>
        public CHARGE CHARGE
        {
            get
            {
                return this.cHARGEField;
            }
            set
            {
                this.cHARGEField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class PRICELIST_USERAREA
    {

        private string qTEIDField;

        private string cOLINX_OEMNUMField;

        private string rEQUEST_FREIGHT_CHARGEField;

        private COLINX_SHIPINSTR cOLINX_SHIPINSTRField;

        private OPERAMT[] oPERAMTField;

        private QUANTITY qUANTITYField;

        private CHARGE[] cHARGEField;

        /// <remarks/>
        public string QTEID
        {
            get
            {
                return this.qTEIDField;
            }
            set
            {
                this.qTEIDField = value;
            }
        }

        /// <remarks/>
        public string COLINX_OEMNUM
        {
            get
            {
                return this.cOLINX_OEMNUMField;
            }
            set
            {
                this.cOLINX_OEMNUMField = value;
            }
        }

        /// <remarks/>
        public string REQUEST_FREIGHT_CHARGE
        {
            get
            {
                return this.rEQUEST_FREIGHT_CHARGEField;
            }
            set
            {
                this.rEQUEST_FREIGHT_CHARGEField = value;
            }
        }

        /// <remarks/>
        public COLINX_SHIPINSTR COLINX_SHIPINSTR
        {
            get
            {
                return this.cOLINX_SHIPINSTRField;
            }
            set
            {
                this.cOLINX_SHIPINSTRField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OPERAMT")]
        public OPERAMT[] OPERAMT
        {
            get
            {
                return this.oPERAMTField;
            }
            set
            {
                this.oPERAMTField = value;
            }
        }

        /// <remarks/>
        public QUANTITY QUANTITY
        {
            get
            {
                return this.qUANTITYField;
            }
            set
            {
                this.qUANTITYField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CHARGE")]
        public CHARGE[] CHARGE
        {
            get
            {
                return this.cHARGEField;
            }
            set
            {
                this.cHARGEField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class PRCLSTLINE_USERAREA
    {

        private string cOLINX_INSTOCKField;

        private DATETIME dATETIMEField;

        private QUANTITY[] qUANTITYField;

        private COLINX_STATUS cOLINX_STATUSField;

        private string cOLINX_DISCCLASSField;

        private SITELEVEL sITELEVELField;

        private MANUFACTURE mANUFACTUREField;

        private SHIPMENT_OPTION[] sHIPMENT_OPTIONField;

        private COLINX_PRODAVAIL[] cOLINX_PRODAVAILField;

        private COLINX_QTEREF cOLINX_QTEREFField;

        private string iTEMTYPEField;

        private CHARGE[] cHARGEField;

        private OPERAMT oPERAMTField;

        private string cOLINX_CONTRACTDESCField;

        private string pRICING_REFERENCEField;

        private SPECIAL_INSTRUCTION[] sPECIAL_INSTRUCTIONSField;

        /// <remarks/>
        public string COLINX_INSTOCK
        {
            get
            {
                return this.cOLINX_INSTOCKField;
            }
            set
            {
                this.cOLINX_INSTOCKField = value;
            }
        }

        /// <remarks/>
        public DATETIME DATETIME
        {
            get
            {
                return this.dATETIMEField;
            }
            set
            {
                this.dATETIMEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("QUANTITY")]
        public QUANTITY[] QUANTITY
        {
            get
            {
                return this.qUANTITYField;
            }
            set
            {
                this.qUANTITYField = value;
            }
        }

        /// <remarks/>
        public COLINX_STATUS COLINX_STATUS
        {
            get
            {
                return this.cOLINX_STATUSField;
            }
            set
            {
                this.cOLINX_STATUSField = value;
            }
        }

        /// <remarks/>
        public string COLINX_DISCCLASS
        {
            get
            {
                return this.cOLINX_DISCCLASSField;
            }
            set
            {
                this.cOLINX_DISCCLASSField = value;
            }
        }

        /// <remarks/>
        public SITELEVEL SITELEVEL
        {
            get
            {
                return this.sITELEVELField;
            }
            set
            {
                this.sITELEVELField = value;
            }
        }

        /// <remarks/>
        public MANUFACTURE MANUFACTURE
        {
            get
            {
                return this.mANUFACTUREField;
            }
            set
            {
                this.mANUFACTUREField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SHIPMENT_OPTION")]
        public SHIPMENT_OPTION[] SHIPMENT_OPTION
        {
            get
            {
                return this.sHIPMENT_OPTIONField;
            }
            set
            {
                this.sHIPMENT_OPTIONField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("COLINX_PRODAVAIL")]
        public COLINX_PRODAVAIL[] COLINX_PRODAVAIL
        {
            get
            {
                return this.cOLINX_PRODAVAILField;
            }
            set
            {
                this.cOLINX_PRODAVAILField = value;
            }
        }

        /// <remarks/>
        public COLINX_QTEREF COLINX_QTEREF
        {
            get
            {
                return this.cOLINX_QTEREFField;
            }
            set
            {
                this.cOLINX_QTEREFField = value;
            }
        }

        /// <remarks/>
        public string ITEMTYPE
        {
            get
            {
                return this.iTEMTYPEField;
            }
            set
            {
                this.iTEMTYPEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CHARGE")]
        public CHARGE[] CHARGE
        {
            get
            {
                return this.cHARGEField;
            }
            set
            {
                this.cHARGEField = value;
            }
        }

        /// <remarks/>
        public OPERAMT OPERAMT
        {
            get
            {
                return this.oPERAMTField;
            }
            set
            {
                this.oPERAMTField = value;
            }
        }

        /// <remarks/>
        public string COLINX_CONTRACTDESC
        {
            get
            {
                return this.cOLINX_CONTRACTDESCField;
            }
            set
            {
                this.cOLINX_CONTRACTDESCField = value;
            }
        }

        /// <remarks/>
        public string PRICING_REFERENCE
        {
            get
            {
                return this.pRICING_REFERENCEField;
            }
            set
            {
                this.pRICING_REFERENCEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SPECIAL_INSTRUCTION", IsNullable = false)]
        public SPECIAL_INSTRUCTION[] SPECIAL_INSTRUCTIONS
        {
            get
            {
                return this.sPECIAL_INSTRUCTIONSField;
            }
            set
            {
                this.sPECIAL_INSTRUCTIONSField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class LINEPRCBRK_USERAREA
    {

        private string cOLINX_PRICETYPEField;

        private string cOLINX_BREAKSEQField;

        private string cOLINX_DISCMULTField;

        private string cOLINX_HOWPRICEDField;

        private string cOLINX_PRICEREFField;

        /// <remarks/>
        public string COLINX_PRICETYPE
        {
            get
            {
                return this.cOLINX_PRICETYPEField;
            }
            set
            {
                this.cOLINX_PRICETYPEField = value;
            }
        }

        /// <remarks/>
        public string COLINX_BREAKSEQ
        {
            get
            {
                return this.cOLINX_BREAKSEQField;
            }
            set
            {
                this.cOLINX_BREAKSEQField = value;
            }
        }

        /// <remarks/>
        public string COLINX_DISCMULT
        {
            get
            {
                return this.cOLINX_DISCMULTField;
            }
            set
            {
                this.cOLINX_DISCMULTField = value;
            }
        }

        /// <remarks/>
        public string COLINX_HOWPRICED
        {
            get
            {
                return this.cOLINX_HOWPRICEDField;
            }
            set
            {
                this.cOLINX_HOWPRICEDField = value;
            }
        }

        /// <remarks/>
        public string COLINX_PRICEREF
        {
            get
            {
                return this.cOLINX_PRICEREFField;
            }
            set
            {
                this.cOLINX_PRICEREFField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class SHOW_PRICELIST_002
    {

        private CNTROLAREA cNTROLAREAField;

        private DATAAREA[] dATAAREAField;

        /// <remarks/>
        public CNTROLAREA CNTROLAREA
        {
            get
            {
                return this.cNTROLAREAField;
            }
            set
            {
                this.cNTROLAREAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DATAAREA")]
        public DATAAREA[] DATAAREA
        {
            get
            {
                return this.dATAAREAField;
            }
            set
            {
                this.dATAAREAField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class DATAAREA
    {

        private SHOW_PRICELIST sHOW_PRICELISTField;

        /// <remarks/>
        public SHOW_PRICELIST SHOW_PRICELIST
        {
            get
            {
                return this.sHOW_PRICELISTField;
            }
            set
            {
                this.sHOW_PRICELISTField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class SHOW_PRICELIST
    {

        private PRICELIST pRICELISTField;

        /// <remarks/>
        public PRICELIST PRICELIST
        {
            get
            {
                return this.pRICELISTField;
            }
            set
            {
                this.pRICELISTField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class PRICELIST
    {

        private DATETIME[] dATETIMEField;

        private string pRICELSTIDField;

        private string cURRENCYField;

        private string dESCRIPTNField;

        private string pRICELSTRVField;

        private string pARTNRIDField;

        private PRICELIST_USERAREA pRICELIST_USERAREAField;

        private PRCLSTLINE[] pRCLSTLINEField;

        private LISTPRCBRK[] lISTPRCBRKField;

        private PRCLSTQUAL[] pRCLSTQUALField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DATETIME")]
        public DATETIME[] DATETIME
        {
            get
            {
                return this.dATETIMEField;
            }
            set
            {
                this.dATETIMEField = value;
            }
        }

        /// <remarks/>
        public string PRICELSTID
        {
            get
            {
                return this.pRICELSTIDField;
            }
            set
            {
                this.pRICELSTIDField = value;
            }
        }

        /// <remarks/>
        public string CURRENCY
        {
            get
            {
                return this.cURRENCYField;
            }
            set
            {
                this.cURRENCYField = value;
            }
        }

        /// <remarks/>
        public string DESCRIPTN
        {
            get
            {
                return this.dESCRIPTNField;
            }
            set
            {
                this.dESCRIPTNField = value;
            }
        }

        /// <remarks/>
        public string PRICELSTRV
        {
            get
            {
                return this.pRICELSTRVField;
            }
            set
            {
                this.pRICELSTRVField = value;
            }
        }

        /// <remarks/>
        public string PARTNRID
        {
            get
            {
                return this.pARTNRIDField;
            }
            set
            {
                this.pARTNRIDField = value;
            }
        }

        /// <remarks/>
        public PRICELIST_USERAREA PRICELIST_USERAREA
        {
            get
            {
                return this.pRICELIST_USERAREAField;
            }
            set
            {
                this.pRICELIST_USERAREAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PRCLSTLINE")]
        public PRCLSTLINE[] PRCLSTLINE
        {
            get
            {
                return this.pRCLSTLINEField;
            }
            set
            {
                this.pRCLSTLINEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LISTPRCBRK")]
        public LISTPRCBRK[] LISTPRCBRK
        {
            get
            {
                return this.lISTPRCBRKField;
            }
            set
            {
                this.lISTPRCBRKField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PRCLSTQUAL")]
        public PRCLSTQUAL[] PRCLSTQUAL
        {
            get
            {
                return this.pRCLSTQUALField;
            }
            set
            {
                this.pRCLSTQUALField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class PRCLSTLINE
    {

        private OPERAMT[] oPERAMTField;

        private string dESCRIPTNField;

        private string lINENUMField;

        private PARTREF[] pARTREFField;

        private PRCLSTLINE_USERAREA pRCLSTLINE_USERAREAField;

        private LINEPRCBRK[] lINEPRCBRKField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OPERAMT")]
        public OPERAMT[] OPERAMT
        {
            get
            {
                return this.oPERAMTField;
            }
            set
            {
                this.oPERAMTField = value;
            }
        }

        /// <remarks/>
        public string DESCRIPTN
        {
            get
            {
                return this.dESCRIPTNField;
            }
            set
            {
                this.dESCRIPTNField = value;
            }
        }

        /// <remarks/>
        public string LINENUM
        {
            get
            {
                return this.lINENUMField;
            }
            set
            {
                this.lINENUMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PARTREF")]
        public PARTREF[] PARTREF
        {
            get
            {
                return this.pARTREFField;
            }
            set
            {
                this.pARTREFField = value;
            }
        }

        /// <remarks/>
        public PRCLSTLINE_USERAREA PRCLSTLINE_USERAREA
        {
            get
            {
                return this.pRCLSTLINE_USERAREAField;
            }
            set
            {
                this.pRCLSTLINE_USERAREAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LINEPRCBRK")]
        public LINEPRCBRK[] LINEPRCBRK
        {
            get
            {
                return this.lINEPRCBRKField;
            }
            set
            {
                this.lINEPRCBRKField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class LINEPRCBRK
    {

        private string dESCRIPTNField;

        private LINEPRCBRK_USERAREA lINEPRCBRK_USERAREAField;

        private object itemField;

        private string oVERIDPRICField;

        /// <remarks/>
        public string DESCRIPTN
        {
            get
            {
                return this.dESCRIPTNField;
            }
            set
            {
                this.dESCRIPTNField = value;
            }
        }

        /// <remarks/>
        public LINEPRCBRK_USERAREA LINEPRCBRK_USERAREA
        {
            get
            {
                return this.lINEPRCBRK_USERAREAField;
            }
            set
            {
                this.lINEPRCBRK_USERAREAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AMOUNT", typeof(AMOUNT))]
        [System.Xml.Serialization.XmlElementAttribute("QUANTITY", typeof(QUANTITY))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        public string OVERIDPRIC
        {
            get
            {
                return this.oVERIDPRICField;
            }
            set
            {
                this.oVERIDPRICField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class LISTPRCBRK
    {

        private AMOUNT aMOUNTField;

        private string dESCRIPTNField;

        private USERAREA uSERAREAField;

        /// <remarks/>
        public AMOUNT AMOUNT
        {
            get
            {
                return this.aMOUNTField;
            }
            set
            {
                this.aMOUNTField = value;
            }
        }

        /// <remarks/>
        public string DESCRIPTN
        {
            get
            {
                return this.dESCRIPTNField;
            }
            set
            {
                this.dESCRIPTNField = value;
            }
        }

        /// <remarks/>
        public USERAREA USERAREA
        {
            get
            {
                return this.uSERAREAField;
            }
            set
            {
                this.uSERAREAField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/colinx_show_pricelist_002")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/colinx_show_pricelist_002", IsNullable = false)]
    public partial class PRCLSTQUAL
    {

        private string dESCRIPTNField;

        private SITELEVEL[] sITELEVELField;

        private USERAREA uSERAREAField;

        private string cATALGNAMEField;

        private string pARTNRIDField;

        /// <remarks/>
        public string DESCRIPTN
        {
            get
            {
                return this.dESCRIPTNField;
            }
            set
            {
                this.dESCRIPTNField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SITELEVEL")]
        public SITELEVEL[] SITELEVEL
        {
            get
            {
                return this.sITELEVELField;
            }
            set
            {
                this.sITELEVELField = value;
            }
        }

        /// <remarks/>
        public USERAREA USERAREA
        {
            get
            {
                return this.uSERAREAField;
            }
            set
            {
                this.uSERAREAField = value;
            }
        }

        /// <remarks/>
        public string CATALGNAME
        {
            get
            {
                return this.cATALGNAMEField;
            }
            set
            {
                this.cATALGNAMEField = value;
            }
        }

        /// <remarks/>
        public string PARTNRID
        {
            get
            {
                return this.pARTNRIDField;
            }
            set
            {
                this.pARTNRIDField = value;
            }
        }
    }
}